<?php $decisionLabels=['accepted'=>'Vollständig akzeptiert','partially_accepted'=>'Teilweise akzeptiert','rejected'=>'Abgelehnt'];$statusLabels=['archived'=>'Archiviert','rejected'=>'Abgelehnt','paid'=>'Ausgezahlt','completed'=>'Abgeschlossen'];?>
<main class="section">
<div class="admin-page-intro"><div><span class="eyebrow">Historie</span><h1>Auftragsarchiv</h1><p>Abgeschlossene, ausgezahlte und abgelehnte Aufträge gezielt wiederfinden.</p></div></div>
<form method="get" class="card filters">
<input type="search" name="q" value="<?=App\Core\View::e($filterTerm)?>" placeholder="Auftrag, Verkäuferin, E-Mail oder Angebot">
<select name="decision"><option value="">Alle Entscheidungen</option><option value="accepted" <?=$filterDecision==='accepted'?'selected':''?>>Vollständig akzeptiert</option><option value="partially_accepted" <?=$filterDecision==='partially_accepted'?'selected':''?>>Teilweise akzeptiert</option><option value="rejected" <?=$filterDecision==='rejected'?'selected':''?>>Abgelehnt</option></select>
<select name="year"><option value="">Alle Jahre</option><?php foreach($years as $y):?><option value="<?=$y?>" <?=$filterYear==(string)$y?'selected':''?>><?=$y?></option><?php endforeach;?></select>
<button class="btn primary">Filtern</button><a class="btn ghost" href="/admin/archiv">Zurücksetzen</a>
</form>
<div class="worklist"><?php foreach($orders as $o):?><a class="work-row" href="/admin/auftraege/<?=$o['id']?>"><div><b>#<?=App\Core\View::e($o['order_number'])?> · <?=App\Core\View::e($o['title'])?></b><span><?=App\Core\View::e($o['first_name'].' '.$o['last_name'])?> · <?=App\Core\View::e($o['email'])?><?php if($o['decision']):?> · <?=App\Core\View::e($decisionLabels[$o['decision']]??$o['decision'])?><?php else:?> · <?=App\Core\View::e($statusLabels[$o['status']]??$o['status'])?><?php endif;?></span></div><strong><?=number_format((float)($o['paid_out_amount']??0),2,',','.')?> / <?=number_format((float)($o['approved_amount']??0),2,',','.')?> € ausgezahlt</strong></a><?php endforeach;?><?php if(!$orders):?><div class="empty">Für diese Filter wurden keine archivierten Aufträge gefunden.</div><?php endif;?></div>
</main>