<main class="section narrow"><a class="back" href="/admin/angebote">← Angebote</a><span class="eyebrow">Angebotsverwaltung</span><h1><?= $offer?'Angebot bearbeiten':'Neues Angebot' ?></h1>
<?php if($offer):?><div class="notice">Beim Speichern entsteht automatisch eine neue Angebotsversion. Bereits angenommene Aufträge behalten ihren damaligen Snapshot.</div><div class="row-actions offer-actions"><form method="post" action="/admin/angebote/<?=$offer['id']?>/duplizieren"><?=App\Core\Csrf::field()?><button class="btn">Als neues Angebot duplizieren</button></form><form method="post" action="/admin/angebote/<?=$offer['id']?>/vorlage"><?=App\Core\Csrf::field()?><button class="btn">Als Vorlage speichern</button></form></div><?php endif;?>
<form method="post" class="card admin-form form-grid"><?=App\Core\Csrf::field()?>
<label class="full">Titel<input name="title" value="<?=App\Core\View::e($offer['title']??'')?>" required></label>
<label>Kategorie<select name="category_id" required><?php foreach($categories as $c):?><option value="<?=$c['id']?>" <?=((string)($offer['category_id']??'')===(string)$c['id'])?'selected':''?>><?=App\Core\View::e($c['name'])?></option><?php endforeach;?></select></label>
<label>Status<select name="status"><option value="draft" <?=($offer['status']??'')==='draft'?'selected':''?>>Entwurf</option><option value="active" <?=($offer['status']??'')==='active'?'selected':''?>>Aktiv</option><option value="disabled" <?=($offer['status']??'')==='disabled'?'selected':''?>>Deaktiviert</option></select></label>
<label class="full">Beschreibung<textarea name="description" rows="8" required><?=App\Core\View::e($version['description']??'')?></textarea></label>
<label>Gesamt-Grundvergütung (€)<input name="compensation" type="number" step="0.01" min="0" value="<?=App\Core\View::e($version['compensation']??'')?>" required></label>
<label>Erfüllungsmodell<select name="fulfillment_model"><?php foreach(['days'=>'X Tage','units'=>'X Einheiten','once'=>'Einmalig','digital'=>'Digital','combined'=>'Kombination'] as $v=>$l):?><option value="<?=$v?>" <?=($version['fulfillment_model']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label>
<label>Dauer / Anzahl<input name="duration_value" type="number" min="1" value="<?=App\Core\View::e($version['duration_value']??'')?>"></label><label>Einheit<input name="duration_unit" value="<?=App\Core\View::e($version['duration_unit']??'Tage')?>"></label>
<label class="check full"><input type="checkbox" name="is_private" value="1" <?=!empty($offer['is_private'])?'checked':''?>><span>Individuelles Privatangebot</span></label><label>Verkäuferin-ID<input name="seller_id" type="number" min="1" value="<?=App\Core\View::e($offer['seller_id']??'')?>"></label><label>Annahmefrist<input name="acceptance_deadline" type="datetime-local" value="<?=!empty($offer['acceptance_deadline'])?date('Y-m-d\TH:i',strtotime($offer['acceptance_deadline'])):''?>"></label>
<?php $jsonFields=['rules_json'=>'Regeln','evidence_json'=>'Nachweise','start_control_json'=>'Startkontrolle','shipping_json'=>'Versand','end_workflow_json'=>'Endworkflow','violation_json'=>'Verstoßlogik','settings_json'=>'Weitere Einstellungen'];foreach($jsonFields as $key=>$label):?><label class="full"><?=$label?> (JSON)<textarea name="<?=$key?>" rows="6"><?=App\Core\View::e(isset($version[$key])?json_encode(json_decode($version[$key],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES):'{}')?></textarea></label><?php endforeach;?>
<label class="full">Optionen (JSON)<textarea name="options_json" rows="9"><?=App\Core\View::e(json_encode(array_map(fn($x)=>['name'=>$x['name'],'description'=>$x['description'],'price'=>(float)$x['price'],'requirements'=>json_decode($x['requirements_json']?:'[]',true),'sort_order'=>(int)$x['sort_order']],$options??[]),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></textarea><small>Jede Option kann Preis, Anforderungen und Sortierung besitzen. Leeres Array = keine Optionen.</small></label>
<label class="full">Kombi-Bestandteile (JSON)<textarea name="components_json" rows="11"><?=App\Core\View::e(json_encode(array_map(fn($x)=>['category_id'=>(int)$x['category_id'],'component_type'=>$x['component_type'],'title'=>$x['title'],'compensation'=>(float)$x['compensation'],'fulfillment_model'=>$x['fulfillment_model'],'duration_value'=>$x['duration_value']!==null?(int)$x['duration_value']:null,'duration_unit'=>$x['duration_unit'],'config'=>json_decode($x['config_json']?:'[]',true),'sort_order'=>(int)$x['sort_order']],$components??[]),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></textarea><small>Nur für Kombi-Angebote erforderlich. Jeder Bestandteil erhält eigene Kategorie, Vergütung, Fristen/Nachweise und Erfüllungslogik.</small></label>
<label class="full">Vorgeplante Zusatzaufgaben (JSON)<textarea name="offer_tasks_json" rows="9"><?=App\Core\View::e(json_encode(array_map(fn($x)=>['task_template_id'=>$x['task_template_id']!==null?(int)$x['task_template_id']:null,'title'=>$x['title'],'config'=>json_decode($x['config_json']?:'[]',true),'sort_order'=>(int)$x['sort_order']],$offerTasks??[]),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></textarea></label>
<button class="btn primary full"><?=$offer?'Neue Version speichern':'Angebot anlegen'?></button></form>
<section class="card"><h2>Kategorie-IDs für Kombi-Bestandteile</h2><div class="chip-list"><?php foreach($categories as $c):?><span class="pill">#<?=$c['id']?> · <?=App\Core\View::e($c['name'])?><?=!empty($c['is_digital'])?' · digital':''?></span><?php endforeach;?></div></section></main>