<?php $physicalComponents=array_values(array_filter($components,fn($x)=>$x['component_type']==='physical'));?>
<main class="section"><div class="section-head"><div><span class="eyebrow">Auftrag #<?=App\Core\View::e($order['order_number'])?></span><h1><?=App\Core\View::e($order['title'])?></h1><p class="muted"><?=App\Core\View::e($order['first_name'].' '.$order['last_name'])?> · <?=App\Core\View::e($order['email'])?> · <?=App\Core\View::e($order['status'])?><?=count($components)>1?' · Kombi-Auftrag':''?></p></div><div class="actions"><strong class="price"><?=number_format((float)$order['current_total'],2,',','.')?> €</strong><a class="btn" href="/admin">Dashboard</a></div></div>
<section><h2>Auftragsbestandteile</h2><div class="worklist"><?php foreach($components as $co):?><div class="work-row"><div><b><?=App\Core\View::e($co['title'])?></b><span><?=App\Core\View::e($co['category_name'])?> · <?=App\Core\View::e($co['component_type'])?> · <?=App\Core\View::e($co['status'])?><?php if($co['duration_value']):?> · <?= (int)$co['duration_value'] ?> <?=App\Core\View::e($co['duration_unit']??'')?><?php endif;?></span></div><strong><?=number_format((float)$co['compensation'],2,',','.')?> €</strong></div><?php endforeach;?></div></section>
<?php if(!$order['started_at'] && $physicalComponents):?><section><div class="section-head compact"><div><h2>Vorabkontrolle</h2><p class="muted">Jede Perspektive wird separat akzeptiert oder beanstandet.</p></div><form method="post" action="/admin/auftraege/<?=$order['id']?>/vorab-freigeben"><?=App\Core\Csrf::field()?><button class="btn primary">Alle Vorabkontrollen prüfen & Durchführung starten</button></form></div><div class="worklist"><?php foreach($precheckRequirements as $pr):?><div class="work-row"><div><b><?=App\Core\View::e($pr['component_title'])?> · <?=App\Core\View::e($pr['label'])?></b><span><?=$pr['accepted_count']?>/<?=$pr['required_count']?> akzeptiert · <?=$pr['pending_count']?> offen · <?=$pr['rejected_count']?> beanstandet</span></div><strong><?=((int)$pr['accepted_count']>=(int)$pr['required_count'])?'vollständig':'offen'?></strong></div><?php endforeach;?></div></section><?php endif;?>
<section><h2>Nachweise</h2><div class="media-grid"><?php foreach($evidences as $e):?><div class="card media-card"><img src="/media/evidence/<?=$e['id']?>" alt="Nachweis"><div><b><?=App\Core\View::e($e['component_title']??'')?><?=!empty($e['component_title'])?' · ':''?><?=App\Core\View::e($e['precheck_label']?:$e['evidence_type'])?></b><span><?=date('d.m.Y H:i',strtotime($e['created_at']))?> · <?=App\Core\View::e($e['review_status'])?></span><?php if($e['review_status']!=='accepted'):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/nachweise/<?=$e['id']?>/pruefen" class="review-form"><?=App\Core\Csrf::field()?><select name="decision"><option value="accepted">Akzeptieren</option><option value="rejected">Beanstanden</option></select><select name="reason"><option value="">Grund</option><option>unscharf</option><option>zu dunkel</option><option>falscher Bildausschnitt</option><option>Produkt nicht vollständig sichtbar</option><option>falsches Motiv</option><option>falsches Timing</option></select><input name="note" placeholder="Hinweis / benötigte Perspektive"><label>Nachforderungsfrist<input type="datetime-local" name="retake_deadline"></label><button class="btn">Speichern</button></form><?php else:?><small>Akzeptierte Aufnahme – bleibt freigegeben.</small><?php endif;?></div></div><?php endforeach;?></div></section>

<section class="split-grid"><div class="card admin-form"><h2>Spontane Fotoanforderung</h2><form method="post" action="/admin/auftraege/<?=$order['id']?>/spontan" class="form-grid"><?=App\Core\Csrf::field()?><label class="full">Betroffener Bestandteil<select name="order_component_id" required><?php foreach($physicalComponents as $co):?><option value="<?=$co['id']?>"><?=App\Core\View::e($co['title'].' · '.$co['category_name'])?></option><?php endforeach;?></select></label><label>Anzahl<input type="number" name="count" min="1" value="1" required></label><label>Deadline<input type="datetime-local" name="deadline" required></label><label class="full">Motiv<input name="motif" required></label><label class="full">Beschreibung<textarea name="description" rows="3"></textarea></label><button class="btn primary full">Anforderung senden</button></form></div><div class="card admin-form"><h2>Zusatzaufgabe</h2><form method="post" action="/admin/auftraege/<?=$order['id']?>/aufgabe" class="form-grid"><?=App\Core\Csrf::field()?><label class="full">Betroffener Bestandteil<select name="order_component_id" required><?php foreach($components as $co):?><option value="<?=$co['id']?>"><?=App\Core\View::e($co['title'].' · '.$co['component_type'])?></option><?php endforeach;?></select></label><label class="full">Vorlage<select name="template_id" required><option value="">Bitte wählen</option><?php foreach($taskTemplates as $tpl):?><option value="<?=$tpl['id']?>"><?=App\Core\View::e($tpl['title'])?></option><?php endforeach;?></select></label><label class="full">Deadline<input type="datetime-local" name="due_at" required></label><button class="btn primary full">Aufgabe hinzufügen</button></form><p class="muted"><a href="/admin/aufgaben">Aufgabenbibliothek verwalten →</a></p></div></section>
<section><h2>Spontane Fotoanforderungen</h2><div class="worklist"><?php foreach($spontaneous as $sr):?><div class="work-row"><div><b><?=App\Core\View::e($sr['component_title']??'')?><?=!empty($sr['component_title'])?' · ':''?><?=App\Core\View::e($sr['motif'])?></b><span><?=$sr['uploaded_count']?>/<?=$sr['requested_count']?> hochgeladen · Frist <?=date('d.m.Y H:i',strtotime($sr['deadline']))?></span></div><strong><?=App\Core\View::e($sr['status'])?></strong></div><?php endforeach;?><?php if(!$spontaneous):?><div class="empty">Keine spontanen Anforderungen.</div><?php endif;?></div></section>
<section><h2>Zusatzaufgaben</h2><div class="worklist"><?php foreach($taskExecutions as $tx):?><div class="work-row"><div><b><?=App\Core\View::e($tx['component_title']??'')?><?=!empty($tx['component_title'])?' · ':''?><?=App\Core\View::e($tx['title'])?></b><span>Fällig <?=date('d.m.Y H:i',strtotime($tx['due_at']))?> · <?=App\Core\View::e($tx['review_status'])?></span><?php if($tx['response_json']): $taskResponse=json_decode($tx['response_json'],true)?:[];?><small><?php foreach($taskResponse as $rk=>$rv):?><?=App\Core\View::e((string)$rk)?>: <?=App\Core\View::e(is_array($rv)?implode(', ',array_map('strval',$rv)):(string)$rv)?><?php if($rk!==array_key_last($taskResponse)):?> · <?php endif;?><?php endforeach;?></small><?php endif;?></div><?php if($tx['submitted_at'] && !in_array($tx['review_status'],['accepted','rejected'],true)):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/aufgaben/<?=$tx['id']?>/pruefen" class="row-actions"><?=App\Core\Csrf::field()?><button class="btn primary" name="decision" value="accepted">Akzeptieren</button><button class="btn" name="decision" value="rejected">Nicht ausreichend</button></form><?php endif;?></div><?php endforeach;?><?php if(!$taskExecutions):?><div class="empty">Keine Zusatzaufgaben.</div><?php endif;?></div></section>
<section><h2>Beschädigungsvorgänge</h2><?php foreach($damageCases as $dc):?><div class="card admin-form"><div class="section-head compact"><div><h3>Vorgang #<?=$dc['id']?><?=!empty($dc['component_title'])?' · '.App\Core\View::e($dc['component_title']):''?></h3><p class="muted"><?=App\Core\View::e($dc['reason'])?> · <?=App\Core\View::e($dc['status'])?></p></div></div><?php if(!in_array($dc['status'],['rejected','restart_started'],true)):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/beschaedigung/<?=$dc['id']?>/nachfordern" class="form-grid"><?=App\Core\Csrf::field()?><label>Nachweistyp<select name="field_type"><option value="photo">Foto</option><option value="video">Video</option><option value="text">Freitext</option></select></label><label>Deadline<input type="datetime-local" name="deadline" required></label><label class="full">Genaue Anforderung<textarea name="instructions" rows="2" required></textarea></label><button class="btn full">Nachweis nachfordern</button></form><form method="post" action="/admin/auftraege/<?=$order['id']?>/beschaedigung/<?=$dc['id']?>/entscheiden" class="form-grid damage-decision"><?=App\Core\Csrf::field()?><label class="full">Entscheidungsnotiz<textarea name="note" rows="2"></textarea></label><button class="btn primary" name="decision" value="recognized">Beschädigung anerkennen & Neustart</button><button class="btn" name="decision" value="rejected">Beschädigung ablehnen</button></form><?php endif;?></div><?php endforeach;?><?php if(!$damageCases):?><div class="empty">Keine Beschädigungsvorgänge.</div><?php endif;?><?php if($damageRequests):?><div class="worklist"><?php foreach($damageRequests as $dr):?><div class="work-row"><div><b>Nachforderung #<?=$dr['id']?> · <?=App\Core\View::e($dr['field_type'])?></b><span><?=App\Core\View::e($dr['instructions'])?> · <?=App\Core\View::e($dr['status'])?></span></div></div><?php endforeach;?></div><?php endif;?></section>
<section><h2>Verstöße</h2><div class="worklist"><?php foreach($violations as $v):?><div class="work-row"><div><b><?=App\Core\View::e($v['component_title']??'')?><?=!empty($v['component_title'])?' · ':''?><?=App\Core\View::e($v['violation_type'])?></b><span><?=App\Core\View::e($v['description'])?> · <?=App\Core\View::e($v['status'])?></span></div><?php if(!in_array($v['status'],['confirmed','discarded'],true)):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/verstoesse/<?=$v['id']?>" class="row-actions"><?=App\Core\Csrf::field()?><button class="btn primary" name="decision" value="confirmed">Bestätigen +1 Tag</button><button class="btn" name="decision" value="discarded">Verwerfen</button></form><?php endif;?></div><?php endforeach;?><?php if(!$violations):?><div class="empty">Keine Verstöße.</div><?php endif;?></div></section>
<section class="split-grid">
<div class="card admin-form"><h2>Auftragswert anpassen / Bonus</h2><form method="post" action="/admin/auftraege/<?=$order['id']?>/anpassung" class="form-grid"><?=App\Core\Csrf::field()?>
<label>Art<select name="adjustment_type"><option value="bonus">Bonus</option><option value="price_change">Preisänderung</option><option value="shipping_subsidy">Versandzuschuss</option><option value="other">Sonstige Anpassung</option></select></label>
<label>Betrag (€)<input name="amount" type="number" step="0.01" required></label>
<label>Gültig ab Durchführungstag<input name="effective_day_no" type="number" min="1"></label>
<label class="full">Bezeichnung / Grund<input name="label" required></label>
<button class="btn primary full">Anpassung speichern</button></form></div>
<div class="card admin-form"><h2>Optionen im laufenden Auftrag</h2><?php if($availableOptions):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/option" class="form-grid"><?=App\Core\Csrf::field()?><label class="full">Option<select name="offer_option_id"><?php foreach($availableOptions as $op):?><option value="<?=$op['id']?>"><?=App\Core\View::e($op['name'])?> · <?=number_format((float)$op['price'],2,',','.')?> €</option><?php endforeach;?></select></label><button class="btn primary full">Option hinzufügen</button></form><?php else:?><p class="muted">Keine weiteren Optionen dieser Angebotsversion verfügbar.</p><?php endif;?>
<div class="worklist"><?php foreach($orderOptions as $op):?><div class="work-row"><div><b><?=App\Core\View::e($op['name'])?></b><span><?=number_format((float)$op['price'],2,',','.')?> €</span></div><form method="post" action="/admin/auftraege/<?=$order['id']?>/option/<?=$op['id']?>/entfernen"><?=App\Core\Csrf::field()?><button class="btn ghost">Entfernen</button></form></div><?php endforeach;?></div></div>
</section>
<section><h2>Preis-/Bonushistorie</h2><div class="worklist"><?php foreach($adjustments as $a):?><div class="work-row"><div><b><?=App\Core\View::e($a['label'])?></b><span><?=App\Core\View::e($a['adjustment_type'])?> · <?=date('d.m.Y H:i',strtotime($a['created_at']))?><?php if($a['effective_day_no']):?> · ab Tag <?=$a['effective_day_no']?><?php endif;?> · <?=App\Core\View::e($a['status'])?></span></div><div class="row-actions"><strong><?=($a['amount']>=0?'+ ':'')?><?=number_format((float)$a['amount'],2,',','.')?> €</strong><?php if($a['adjustment_type']==='bonus'&&$a['status']==='reserved'):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/bonus/<?=$a['id']?>/entfernen"><?=App\Core\Csrf::field()?><button class="btn ghost">Bonus entfernen</button></form><?php endif;?></div></div><?php endforeach;?><?php if(!$adjustments):?><div class="empty">Noch keine nachträglichen Anpassungen.</div><?php endif;?></div></section>
<section class="card admin-form"><h2>Manueller Zusatztag</h2><form method="post" action="/admin/auftraege/<?=$order['id']?>/zusatztage" class="form-grid"><?=App\Core\Csrf::field()?><label class="full">Betroffener physischer Bestandteil<select name="order_component_id" required><?php foreach($physicalComponents as $co):?><option value="<?=$co['id']?>"><?=App\Core\View::e($co['title'].' · '.$co['category_name'])?></option><?php endforeach;?></select></label><label class="full">Vollständiger Grund<textarea name="reason" rows="2" required></textarea></label><label class="check"><input type="checkbox" name="is_paid" value="1"> Bezahlt</label><label>Betrag (€)<input name="amount" type="number" step="0.01" min="0"></label><button class="btn primary full">Zusatztag anhängen</button></form></section>
<?php if($digitalComponents):?><section><h2>Digitale Prüfung & Revisionen</h2>
<?php foreach($digitalComponents as $dc): $req=json_decode($dc['requirements_json']?:'{}',true)?:[];$versions=$digitalVersions[$dc['id']]??[];?>
<div class="card admin-form"><div class="section-head compact"><div><h3><?=App\Core\View::e($req['title']??$dc['component_title'])?></h3><p class="muted">Status <?=App\Core\View::e($dc['status'])?> · Format <?=App\Core\View::e($dc['format_type'])?></p></div><strong><?=number_format((float)$dc['compensation'],2,',','.')?> €</strong></div>
<div class="worklist"><?php foreach($versions as $v):?><div class="card"><div class="section-head compact"><b>V<?=$v['version_no']?> · <?=App\Core\View::e($v['content_type'])?></b><span><?=date('d.m.Y H:i',strtotime($v['created_at']))?> · <?=App\Core\View::e($v['submission_status'])?></span></div>
<?php if($v['content_type']==='text'):?><div class="digital-text"><?=nl2br(App\Core\View::e($v['text_content']))?></div>
<?php elseif(str_starts_with((string)$v['mime_type'],'audio/')):?><audio controls preload="metadata" src="/media/digital/<?=$v['id']?>"></audio>
<?php else:?><video controls preload="metadata" src="/media/digital/<?=$v['id']?>"></video><?php endif;?>
<p><a class="btn ghost" href="/media/digital/<?=$v['id']?>?download=1">Version herunterladen</a></p></div><?php endforeach;?><?php if(!$versions):?><div class="empty">Noch keine digitale Version.</div><?php endif;?></div>
<?php foreach(($revisionRounds[$dc['id']]??[]) as $rr):?><div class="card"><h4>Revision <?=$rr['round_no']?> · <?=App\Core\View::e($rr['status'])?></h4><p>Deadline <?=date('d.m.Y H:i',strtotime($rr['deadline']))?> · Nachfrist <?=date('d.m.Y H:i',strtotime($rr['grace_ends_at']))?></p>
<div class="worklist"><?php foreach(($revisionItems[$rr['id']]??[]) as $ri):?><div class="work-row"><div><b><?=App\Core\View::e($ri['description'])?></b><span><?=App\Core\View::e($ri['status'])?></span></div><form method="post" action="/admin/auftraege/<?=$order['id']?>/revision/<?=$ri['id']?>" class="row-actions"><?=App\Core\Csrf::field()?><select name="status"><option value="open" <?=$ri['status']==='open'?'selected':''?>>Offen</option><option value="done" <?=$ri['status']==='done'?'selected':''?>>Erledigt</option><option value="insufficient" <?=$ri['status']==='insufficient'?'selected':''?>>Nicht ausreichend</option><option value="change_again" <?=$ri['status']==='change_again'?'selected':''?>>Erneut ändern</option></select><button class="btn">Speichern</button></form></div><?php endforeach;?></div></div><?php endforeach;?>
<?php if(!in_array($dc['status'],['accepted','partially_accepted','rejected'],true)):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/digital/<?=$dc['id']?>/pruefen" class="form-grid"><?=App\Core\Csrf::field()?>
<label>Entscheidung<select name="decision"><option value="accepted">Akzeptiert</option><option value="revision">Revision erforderlich</option><option value="partially_accepted">Teilweise akzeptiert</option><option value="rejected">Abgelehnt</option></select></label>
<label>Teilfreigabe (€)<input type="number" name="approved_amount" min="0" max="<?=App\Core\View::e($dc['compensation'])?>" step="0.01"></label>
<label>Revisionsfrist<input type="datetime-local" name="deadline"></label>
<label class="full">Revisionspunkte – ein Punkt pro Zeile<textarea name="revision_items" rows="5"></textarea></label>
<label class="full">Prüfhinweis<textarea name="note" rows="3"></textarea></label>
<button class="btn primary full">Digitale Prüfung speichern</button></form><?php endif;?>
</div><?php endforeach;?></section><?php endif;?>
<section><h2>Versand / Wareneingang</h2>
<?php if($physicalComponents && !$shipping && $order['phase']==='execution'):?>
<div class="card admin-form"><h3>Versandphase starten</h3><form method="post" action="/admin/auftraege/<?=$order['id']?>/versand/start" class="form-grid"><?=App\Core\Csrf::field()?>
<label class="full">Empfängeradresse<select name="recipient_address_id" required><option value="">Bitte wählen</option><?php foreach($addresses as $a):?><option value="<?=$a['id']?>"><?=App\Core\View::e($a['label'].' · '.$a['recipient_name'].' · '.$a['postal_code'].' '.$a['city'])?></option><?php endforeach;?></select></label>
<button class="btn primary full">Durchführung abschließen & Versand freigeben</button></form><?php if(!$addresses):?><p class="muted">Es ist noch keine aktive Empfängeradresse vorhanden. <a href="/admin/empfaengeradressen">Adresse anlegen →</a></p><?php endif;?></div>
<?php endif;?>
<?php if($shipping):?>
<div class="card"><div class="section-head compact"><div><h3><?=App\Core\View::e($shipping['label']??'Empfängeradresse')?></h3><p><?=App\Core\View::e(($shipping['recipient_name']??'').' · '.($shipping['street']??'').' · '.($shipping['postal_code']??'').' '.($shipping['city']??''))?></p></div><strong><?=App\Core\View::e($shipping['shipment_status']??$shipping['status'])?></strong></div>
<div class="worklist"><?php foreach($shippingSteps as $st):?><div class="work-row"><div><b><?=$st['step_no']?>. <?=App\Core\View::e($st['title'])?></b><span><?=App\Core\View::e($st['instructions']??'')?> · <?=App\Core\View::e($st['status'])?></span></div></div><?php endforeach;?></div>
<?php if(($shipping['shipment_status']??'')==='shipped'):?><form method="post" action="/admin/auftraege/<?=$order['id']?>/wareneingang"><?=App\Core\Csrf::field()?><button class="btn primary">Wareneingang bestätigen</button></form><?php endif;?>
</div>
<?php endif;?>
<?php if(!$finalReview && $order['phase']==='review'):?>
<div class="card admin-form"><h3>Abschlussprüfung</h3><form method="post" action="/admin/auftraege/<?=$order['id']?>/abschlusspruefung" class="form-grid"><?=App\Core\Csrf::field()?>
<label>Entscheidung<select name="decision" required><option value="accepted">Akzeptiert</option><option value="partially_accepted">Teilweise akzeptiert</option><option value="rejected">Abgelehnt</option></select></label>
<label>Teilfreigabe (€)<input type="number" name="approved_amount" min="0" max="<?=App\Core\View::e($order['current_total'])?>" step="0.01"></label>
<label class="full">Mitteilung an Verkäuferin<textarea name="seller_message" rows="3"></textarea></label>
<label class="full">Interne Abschlussnotiz<textarea name="internal_note" rows="3"></textarea></label>
<button class="btn primary full">Abschlussentscheidung speichern</button></form></div>
<?php elseif($finalReview):?><div class="card"><b>Abschlussentscheidung: <?=App\Core\View::e($finalReview['decision'])?></b><p>Freigegeben: <?=number_format((float)$finalReview['approved_amount'],2,',','.')?> €</p><?php if($finalReview['seller_message']):?><p><?=App\Core\View::e($finalReview['seller_message'])?></p><?php endif;?></div><?php endif;?>
</section>
<section><h2>Kalender / Tage</h2><div class="day-grid"><?php foreach($days as $d):?><div class="card day-card"><span><?=date('d.m.Y',strtotime($d['calendar_date']))?></span><strong><?=App\Core\View::e($d['component_title']??'')?><?=!empty($d['component_title'])?' · ':''?><?=App\Core\View::e($d['day_type'])?><?=isset($d['day_no'])?' · '.$d['day_no']:''?></strong><small><?=App\Core\View::e($d['reason']??'')?></small></div><?php endforeach;?></div></section>
<section class="card chat"><h2>Auftragschat</h2><div class="chat-log"><?php foreach($messages as $m):?><div class="message <?=$m['sender_type']?>"><small><?=App\Core\View::e($m['sender_type'])?> · <?=date('d.m. H:i',strtotime($m['created_at']))?></small><p><?=nl2br(App\Core\View::e($m['message']))?></p></div><?php endforeach;?></div><form method="post" action="/admin/auftraege/<?=$order['id']?>/chat" class="chat-form"><?=App\Core\Csrf::field()?><textarea name="message" rows="3" required></textarea><button class="btn primary">Senden</button></form></section></main>