<?php
$fieldLabels=['first_name'=>'Vorname','last_name'=>'Nachname','birth_date'=>'Geburtsdatum','street'=>'Straße','postal_code'=>'PLZ','city'=>'Ort','phone'=>'Telefon','email'=>'E-Mail-Adresse'];
$statusLabels=['precheck'=>'Vorabkontrolle','preparation'=>'Vorbereitung','running'=>'In Durchführung','shipping'=>'Versand','digital_review'=>'Digitale Prüfung','reviewing'=>'Abschlussprüfung','completed'=>'Abgeschlossen','rejected'=>'Abgelehnt','archived'=>'Archiviert','cancelled'=>'Storniert','paid'=>'Ausgezahlt'];
$phaseLabels=['preparation'=>'Vorbereitung','execution'=>'Durchführung','shipping'=>'Versand','review'=>'Prüfung','payout'=>'Auszahlung','archive'=>'Archiv'];
$violationLabels=['missing_evidence'=>'Fehlender Pflichtnachweis','evidence_retake_missed'=>'Versäumte Nachaufnahme','task_not_completed'=>'Zusatzaufgabe nicht erledigt','spontaneous_evidence_missed'=>'Spontanfoto nicht eingereicht','damage_evidence_missed'=>'Schadensnachweis nicht eingereicht','digital_revision_missed'=>'Digitale Revision versäumt','shipping_requirement_missed'=>'Versandschritt nicht erledigt'];
$violationStatus=['open'=>'Offen','reviewed'=>'In Prüfung','confirmed'=>'Bestätigt','discarded'=>'Verworfen'];
$eventLabels=['order_accepted'=>'Auftrag angenommen','order_started'=>'Auftrag gestartet','options_changed'=>'Optionen geändert','seller_data_changed'=>'Stammdaten geändert','seller_anonymized'=>'Konto anonymisiert','order_acceptance_consents'=>'Annahmebestätigungen dokumentiert','order_confirmation_email'=>'Auftragsbestätigung versendet','order_confirmation_email_failed'=>'Auftragsbestätigung fehlgeschlagen','platform_outage'=>'Plattformausfall dokumentiert'];
$actorLabels=['seller'=>'Verkäuferin','admin'=>'Administrator','system'=>'System'];
?>
<main class="section">
<div class="admin-page-intro"><div><span class="eyebrow">Verkäuferinnenakte #<?=$seller['id']?></span><h1><?=App\Core\View::e($seller['first_name'].' '.$seller['last_name'])?></h1><p><?=App\Core\View::e($seller['email'])?> · <?=$seller['email_verified_at']?'E-Mail bestätigt':'E-Mail nicht bestätigt'?><?php if($seller['deleted_at']):?> · Konto anonymisiert<?php endif;?></p></div><a class="btn" href="/admin/verkaeuferinnen">Zur Liste</a></div>

<div class="admin-stat-grid">
<div class="admin-stat"><span>Verfügbar</span><strong><?=number_format((float)($wallet['balance_available']??0),2,',','.')?> €</strong><small>auszahlbar</small></div>
<div class="admin-stat"><span>Vorgemerkt</span><strong><?=number_format((float)($wallet['balance_reserved']??0),2,',','.')?> €</strong><small>laufende Aufträge</small></div>
<div class="admin-stat"><span>In Prüfung</span><strong><?=number_format((float)($wallet['balance_in_review']??0),2,',','.')?> €</strong><small>Abschlussprüfung</small></div>
<div class="admin-stat"><span>Aufträge</span><strong><?=count($orders)?></strong><small>gesamter Verlauf</small></div>
<div class="admin-stat"><span>Verstöße</span><strong><?=count(array_filter($violations,fn($v)=>$v['status']==='confirmed'))?></strong><small>bestätigt</small></div>
<div class="admin-stat"><span>Auszahlungen</span><strong><?=count($payouts)?></strong><small>Anträge</small></div>
</div>

<section class="card admin-form settings-section"><h2>Stammdaten bearbeiten</h2><form method="post" action="/admin/verkaeuferinnen/<?=$seller['id']?>" class="form-grid"><?=App\Core\Csrf::field()?><label>Vorname<input name="first_name" value="<?=App\Core\View::e($seller['first_name'])?>" required></label><label>Nachname<input name="last_name" value="<?=App\Core\View::e($seller['last_name'])?>" required></label><label>Geburtsdatum<input name="birth_date" type="date" value="<?=App\Core\View::e($seller['birth_date'])?>" required></label><label>Telefon<input name="phone" value="<?=App\Core\View::e($seller['phone'])?>" required></label><label class="full">Straße<input name="street" value="<?=App\Core\View::e($seller['street'])?>" required></label><label>PLZ<input name="postal_code" value="<?=App\Core\View::e($seller['postal_code'])?>" required></label><label>Ort<input name="city" value="<?=App\Core\View::e($seller['city'])?>" required></label><label class="full">E-Mail<input name="email" type="email" value="<?=App\Core\View::e($seller['email'])?>" required></label><label class="full">Admin-Passwort <small>(nur bei Änderung von E-Mail oder Geburtsdatum)</small><input name="admin_password" type="password"></label><button class="btn primary full">Änderungen speichern</button></form></section>

<section><div class="section-head compact"><div><h2>Aufträge</h2><p class="muted">Gesamter Auftragsverlauf dieser Verkäuferin.</p></div></div><div class="worklist"><?php foreach($orders as $o):?><a class="work-row" href="/admin/auftraege/<?=$o['id']?>"><div><b>#<?=App\Core\View::e($o['order_number'])?></b><span><?=App\Core\View::e($statusLabels[$o['status']]??$o['status'])?> · <?=App\Core\View::e($phaseLabels[$o['phase']]??$o['phase'])?></span></div><strong><?=number_format((float)$o['current_total'],2,',','.')?> €</strong></a><?php endforeach;?><?php if(!$orders):?><div class="empty">Keine Aufträge.</div><?php endif;?></div></section>

<section><h2>Verstöße / Prüffälle</h2><div class="worklist"><?php foreach($violations as $v):?><a class="work-row" href="/admin/auftraege/<?=$v['order_id']?>"><div><b>Auftrag #<?=App\Core\View::e($v['order_number'])?> · <?=App\Core\View::e($violationLabels[$v['violation_type']]??$v['violation_type'])?></b><span><?=App\Core\View::e($v['description'])?></span></div><strong><?=App\Core\View::e($violationStatus[$v['status']]??$v['status'])?></strong></a><?php endforeach;?><?php if(!$violations):?><div class="empty">Keine Prüffälle.</div><?php endif;?></div></section>

<section><h2>Datenänderungen</h2><div class="worklist"><?php foreach($changes as $x):?><div class="work-row"><div><b><?=App\Core\View::e($fieldLabels[$x['field_name']]??$x['field_name'])?></b><span><?=date('d.m.Y H:i',strtotime($x['changed_at']))?></span></div><small><?=App\Core\View::e($x['old_value'])?> → <?=App\Core\View::e($x['new_value'])?></small></div><?php endforeach;?><?php if(!$changes):?><div class="empty">Keine Änderungen protokolliert.</div><?php endif;?></div></section>

<section><h2>Auszahlungen</h2><div class="worklist"><?php foreach($payouts as $p):?><a class="work-row" href="/admin/auszahlungen"><div><b><?=number_format((float)$p['net_amount'],2,',','.')?> €</b><span>Beantragt <?=date('d.m.Y H:i',strtotime($p['requested_at']))?></span></div><strong><?=App\Core\View::e(['requested'=>'Beantragt','in_review'=>'In Prüfung','approved'=>'Freigegeben','paid'=>'Ausgezahlt','rejected'=>'Abgelehnt','withdrawn'=>'Zurückgezogen'][$p['status']]??$p['status'])?></strong></a><?php endforeach;?><?php if(!$payouts):?><div class="empty">Keine Auszahlungsanträge.</div><?php endif;?></div></section>

<section><h2>Systemereignisse</h2><div class="worklist"><?php foreach($events as $e):?><div class="work-row"><div><b><?=App\Core\View::e($eventLabels[$e['event_type']]??ucfirst(str_replace('_',' ',$e['event_type'])))?></b><span><?=date('d.m.Y H:i',strtotime($e['created_at']))?> · <?=App\Core\View::e($actorLabels[$e['actor_type']]??$e['actor_type'])?></span></div></div><?php endforeach;?><?php if(!$events):?><div class="empty">Keine Systemereignisse.</div><?php endif;?></div></section>

<?php if(!$seller['deleted_at']):?><section class="danger-zone card"><h2>Konto löschen / anonymisieren</h2><p>Personenbezogene Profildaten werden anonymisiert. Erforderliche Geschäfts-, Zahlungs-, Auftrags- und Nachweisdaten bleiben erhalten.</p><form method="post" action="/admin/verkaeuferinnen/<?=$seller['id']?>/loeschen"><?=App\Core\Csrf::field()?><button class="btn" data-confirm="Konto wirklich löschen und anonymisieren?">Konto löschen / anonymisieren</button></form></section><?php endif;?>
</main>