<main class="section"><div class="section-head"><div><span class="eyebrow">System</span><h1>Globale Einstellungen</h1></div><a class="btn ghost" href="/admin">Zurück</a></div>
<section class="card admin-form"><form method="post" action="/admin/einstellungen" class="form-grid"><?=App\Core\Csrf::field()?>
<label>Plattformname<input name="platform_name" value="<?=App\Core\View::e($settings['platform_name']??'FetischShop')?>"></label><label>Kontakt-E-Mail<input type="email" name="contact_email" value="<?=App\Core\View::e($settings['contact_email']??'')?>"></label>
<label>Mindest-Auszahlung (€)<input type="number" step="0.01" name="payout_minimum" value="<?=App\Core\View::e($settings['payout_minimum']??'10.00')?>"></label><label>Auszahlungstage<input name="payout_days" value="<?=App\Core\View::e($settings['payout_days']??'Montag,Donnerstag')?>"></label>
<label>Bank aktiviert<select name="payout_bank_enabled"><option value="1" <?=($settings['payout_bank_enabled']??'1')==='1'?'selected':''?>>Ja</option><option value="0" <?=($settings['payout_bank_enabled']??'1')==='0'?'selected':''?>>Nein</option></select></label>
<label>PayPal aktiviert<select name="payout_paypal_enabled"><option value="1" <?=($settings['payout_paypal_enabled']??'1')==='1'?'selected':''?>>Ja</option><option value="0" <?=($settings['payout_paypal_enabled']??'1')==='0'?'selected':''?>>Nein</option></select></label>
<label>Bank-Gebühr Typ<select name="payout_bank_fee_type"><?php foreach(['none'=>'Keine','fixed'=>'Fix','percent'=>'Prozent'] as $k=>$v):?><option value="<?=$k?>" <?=($settings['payout_bank_fee_type']??'none')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Bank-Gebühr Wert<input type="number" step="0.01" name="payout_bank_fee_value" value="<?=App\Core\View::e($settings['payout_bank_fee_value']??'0')?>"></label>
<label>PayPal-Gebühr Typ<select name="payout_paypal_fee_type"><?php foreach(['none'=>'Keine','fixed'=>'Fix','percent'=>'Prozent'] as $k=>$v):?><option value="<?=$k?>" <?=($settings['payout_paypal_fee_type']??'none')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>PayPal-Gebühr Wert<input type="number" step="0.01" name="payout_paypal_fee_value" value="<?=App\Core\View::e($settings['payout_paypal_fee_value']??'0')?>"></label>
<label>Bild-Upload max. MB<input type="number" name="upload_image_mb" value="<?=App\Core\View::e($settings['upload_image_mb']??'12')?>"></label><label>Digital-Upload max. MB<input type="number" name="upload_digital_mb" value="<?=App\Core\View::e($settings['upload_digital_mb']??'150')?>"></label>
<label>Bald fällig ab Minuten<input type="number" name="escalation_soon_minutes" value="<?=App\Core\View::e($settings['escalation_soon_minutes']??'60')?>"></label><label>Kritisch ab Minuten<input type="number" name="escalation_critical_minutes" value="<?=App\Core\View::e($settings['escalation_critical_minutes']??'15')?>"></label>
<button class="btn primary full">Einstellungen speichern</button></form></section>
<section class="card admin-form"><h2>Technischen Plattformausfall dokumentieren</h2><p class="muted">Aktive Fristen werden automatisch um die Ausfalldauer verschoben.</p><form method="post" action="/admin/einstellungen/ausfall" class="form-grid"><?=App\Core\Csrf::field()?><label>Beginn<input type="datetime-local" name="starts_at" required></label><label>Ende<input type="datetime-local" name="ends_at" required></label><label class="full">Grund<textarea name="reason" rows="2"></textarea></label><button class="btn full">Ausfall dokumentieren</button></form></section>
<section><h2>Ausfallhistorie</h2><div class="worklist"><?php foreach($outages as $o):?><div class="work-row"><div><b><?=date('d.m.Y H:i',strtotime($o['starts_at']))?> – <?=date('d.m.Y H:i',strtotime($o['ends_at']))?></b><span><?=App\Core\View::e($o['reason']??'Systemausfall')?></span></div></div><?php endforeach;?><?php if(!$outages):?><div class="empty">Keine dokumentierten Ausfälle.</div><?php endif;?></div></section></main>