<?php
namespace App\Http\Controllers;
use App\Core\Auth;use App\Core\Request;use App\Core\Response;use App\Core\Session;use App\Core\View;use App\Services\OrderService;use PDO;use DateTimeImmutable;
final class AdminOrderController{
 public function __construct(private string $root,private PDO $db,private Auth $auth){}
 public function show(Request $r,array $p):void{
  $q=$this->db->prepare("SELECT o.*,s.first_name,s.last_name,s.email,ov.title,c.is_digital FROM orders o JOIN sellers s ON s.id=o.seller_id JOIN offer_versions ov ON ov.id=o.offer_version_id JOIN offers off ON off.id=o.offer_id JOIN categories c ON c.id=off.category_id WHERE o.id=?");$q->execute([(int)$p['id']]);$o=$q->fetch();if(!$o)Response::abort(404);
  $e=$this->db->prepare('SELECT * FROM evidences WHERE order_id=? ORDER BY created_at DESC');$e->execute([$o['id']]);$v=$this->db->prepare('SELECT * FROM violations WHERE order_id=? ORDER BY created_at DESC');$v->execute([$o['id']]);$d=$this->db->prepare('SELECT * FROM order_days WHERE order_id=? ORDER BY calendar_date');$d->execute([$o['id']]);
  $sp=$this->db->prepare("SELECT sr.*,(SELECT COUNT(*) FROM evidences x WHERE x.spontaneous_request_id=sr.id) uploaded_count FROM spontaneous_requests sr WHERE sr.order_id=? ORDER BY sr.created_at DESC");$sp->execute([$o['id']]);
  $tasks=$this->db->prepare("SELECT te.*,t.title,t.description,t.config_json FROM task_executions te JOIN tasks t ON t.id=te.task_id WHERE t.order_id=? ORDER BY te.due_at DESC");$tasks->execute([$o['id']]);
  $tpl=$this->db->query("SELECT id,title FROM task_templates WHERE is_active=1 ORDER BY title")->fetchAll();
  $damage=$this->db->prepare("SELECT * FROM damage_cases WHERE order_id=? ORDER BY created_at DESC");$damage->execute([$o['id']]);
  $damageReq=$this->db->prepare("SELECT dr.* FROM damage_evidence_requests dr JOIN damage_cases dc ON dc.id=dr.damage_case_id WHERE dc.order_id=? ORDER BY dr.created_at DESC");$damageReq->execute([$o['id']]);
  $m=$this->db->prepare('SELECT cm.* FROM chat_messages cm JOIN chats c ON c.id=cm.chat_id WHERE c.order_id=? ORDER BY cm.created_at');$m->execute([$o['id']]);
  $shipping=$this->db->prepare("SELECT sw.*,ra.label,ra.recipient_name,ra.street,ra.postal_code,ra.city,ra.country_code,s.status shipment_status,s.tracking_number,s.shipped_at,s.received_at FROM shipping_workflows sw LEFT JOIN recipient_addresses ra ON ra.id=sw.recipient_address_id LEFT JOIN shipments s ON s.shipping_workflow_id=sw.id WHERE sw.order_id=?");$shipping->execute([$o['id']]);$shipping=$shipping->fetch();
  $shippingSteps=[];if($shipping){$ss=$this->db->prepare('SELECT * FROM shipping_steps WHERE shipping_workflow_id=? ORDER BY step_no');$ss->execute([$shipping['id']]);$shippingSteps=$ss->fetchAll();}
  $addresses=$this->db->query("SELECT id,label,recipient_name,street,postal_code,city FROM recipient_addresses WHERE is_active=1 ORDER BY label")->fetchAll();
  $final=$this->db->prepare('SELECT * FROM final_reviews WHERE order_id=?');$final->execute([$o['id']]);$final=$final->fetch();
  $digitalComponents=$this->db->prepare("SELECT dc.*,oc.title component_title FROM digital_components dc JOIN order_components oc ON oc.id=dc.order_component_id WHERE oc.order_id=? ORDER BY dc.id");$digitalComponents->execute([$o['id']]);$digitalComponents=$digitalComponents->fetchAll();
  $digitalVersions=[];$revisionRounds=[];$revisionItems=[];
  foreach($digitalComponents as $dc){
   $v=$this->db->prepare("SELECT dv.*,ds.status submission_status,ds.finalized_at FROM digital_versions dv JOIN digital_submissions ds ON ds.id=dv.digital_submission_id WHERE ds.digital_component_id=? ORDER BY dv.version_no DESC");$v->execute([$dc['id']]);$digitalVersions[$dc['id']]=$v->fetchAll();
   $rr=$this->db->prepare("SELECT * FROM revision_rounds WHERE digital_component_id=? ORDER BY round_no DESC");$rr->execute([$dc['id']]);$revisionRounds[$dc['id']]=$rr->fetchAll();
   foreach($revisionRounds[$dc['id']] as $round){$ri=$this->db->prepare('SELECT * FROM revision_items WHERE revision_round_id=? ORDER BY id');$ri->execute([$round['id']]);$revisionItems[$round['id']]=$ri->fetchAll();}
  }
  View::render($this->root,'admin/order',['pageTitle'=>'Auftrag #'.$o['order_number'],'order'=>$o,'evidences'=>$e->fetchAll(),'violations'=>$v->fetchAll(),'days'=>$d->fetchAll(),'spontaneous'=>$sp->fetchAll(),'taskExecutions'=>$tasks->fetchAll(),'taskTemplates'=>$tpl,'damageCases'=>$damage->fetchAll(),'damageRequests'=>$damageReq->fetchAll(),'messages'=>$m->fetchAll(),'shipping'=>$shipping,'shippingSteps'=>$shippingSteps,'addresses'=>$addresses,'finalReview'=>$final,'digitalComponents'=>$digitalComponents,'digitalVersions'=>$digitalVersions,'revisionRounds'=>$revisionRounds,'revisionItems'=>$revisionItems]);
 }
 public function reviewEvidence(Request $r,array $p):void{$status=(string)$r->input('decision');if(!in_array($status,['accepted','rejected'],true))Response::abort(422);$q=$this->db->prepare('UPDATE evidences SET review_status=?,rejection_reason=?,rejection_note=? WHERE id=? AND order_id=?');$q->execute([$status,$status==='rejected'?(string)$r->input('reason'):null,$status==='rejected'?(string)$r->input('note'):null,(int)$p['evidenceId'],(int)$p['id']]);Session::flash('success','Nachweisentscheidung gespeichert.');Response::redirect('/admin/auftraege/'.$p['id']);}
 public function approvePrecheck(Request $r,array $p):void{try{(new OrderService($this->db))->startAfterPrecheck((int)$p['id']);Session::flash('success','Vorabkontrolle freigegeben. Auftrag wurde unmittelbar gestartet.');}catch(\Throwable $e){Session::flash('error',$e->getMessage());}Response::redirect('/admin/auftraege/'.$p['id']);}
 public function decideViolation(Request $r,array $p):void{
  $decision=(string)$r->input('decision');$id=(int)$p['violationId'];$q=$this->db->prepare('SELECT * FROM violations WHERE id=? AND order_id=?');$q->execute([$id,(int)$p['id']]);$v=$q->fetch();if(!$v)Response::abort(404);
  if($decision==='confirmed'&&$v['status']!=='confirmed'){$this->db->beginTransaction();try{$this->db->prepare("UPDATE violations SET status='confirmed',confirmed_at=NOW(),decided_at=NOW(),provisional_extension=0 WHERE id=?")->execute([$id]);$x=$this->db->prepare('SELECT id FROM extension_days WHERE violation_id=? ORDER BY id LIMIT 1 FOR UPDATE');$x->execute([$id]);$ext=$x->fetchColumn();if($ext){$this->db->prepare('UPDATE extension_days SET is_provisional=0,reason=? WHERE id=?')->execute([$v['description'],$ext]);$ext=(int)$ext;}else{$this->db->prepare("INSERT INTO extension_days(order_id,violation_id,source_type,source_id,reason,is_provisional,is_paid,created_at) VALUES(?,?,'violation',?,?,0,0,NOW())")->execute([$p['id'],$id,$id,$v['description']]);$ext=(int)$this->db->lastInsertId();}$this->appendDay((int)$p['id'],'violation_extension',$ext,$v['description'],false,null);$this->db->commit();}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
  elseif($decision==='discarded'){$this->db->prepare("UPDATE violations SET status='discarded',provisional_extension=0,decided_at=NOW() WHERE id=?")->execute([$id]);$this->db->prepare("DELETE FROM extension_days WHERE violation_id=? AND is_provisional=1")->execute([$id]);}
  Session::flash('success','Verstoßentscheidung gespeichert.');Response::redirect('/admin/auftraege/'.$p['id']);
 }
 public function addManualDay(Request $r,array $p):void{$paid=(bool)$r->input('is_paid');$amount=$paid?(float)$r->input('amount'):null;$reason=trim((string)$r->input('reason'))?:'Manueller Zusatztag';$this->db->beginTransaction();try{$this->db->prepare('INSERT INTO manual_extra_days(order_id,reason,is_paid,amount,created_at) VALUES(?,?,?,?,NOW())')->execute([$p['id'],$reason,(int)$paid,$amount]);$id=(int)$this->db->lastInsertId();$this->appendDay((int)$p['id'],'manual_extension',$id,$reason,$paid,$amount);if($paid){$o=$this->db->prepare('SELECT seller_id FROM orders WHERE id=?');$o->execute([$p['id']]);$sid=(int)$o->fetchColumn();$w=$this->db->prepare('SELECT id FROM wallets WHERE seller_id=? FOR UPDATE');$w->execute([$sid]);$wid=(int)$w->fetchColumn();$this->db->prepare('UPDATE wallets SET balance_reserved=balance_reserved+?,updated_at=NOW() WHERE id=?')->execute([$amount,$wid]);$this->db->prepare("INSERT INTO wallet_entries(wallet_id,order_id,entry_type,status,amount,created_at) VALUES(?,?,'paid_extra_day','reserved',?,NOW())")->execute([$wid,$p['id'],$amount]);$this->db->prepare('UPDATE orders SET current_total=current_total+?,updated_at=NOW() WHERE id=?')->execute([$amount,$p['id']]);}$this->db->commit();Session::flash('success','Zusatztag wurde angehängt.');}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();Session::flash('error',$e->getMessage());}Response::redirect('/admin/auftraege/'.$p['id']);}
 private function appendDay(int $orderId,string $type,int $sourceId,string $reason,bool $paid,?float $amount):void{
  $run=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$orderId]);$rid=(int)$run->fetchColumn();
  $q=$this->db->prepare('SELECT MAX(calendar_date),MAX(COALESCE(day_no,0)) FROM order_days WHERE order_id=? AND order_run_id=?');$q->execute([$orderId,$rid]);$max=$q->fetch(PDO::FETCH_NUM);$date=(new DateTimeImmutable($max[0]?:'today'))->modify('+1 day');$dayNo=(int)$max[1]+1;
  $this->db->prepare("INSERT INTO order_days(order_id,order_run_id,day_no,calendar_date,day_type,source_id,is_paid,paid_amount,reason,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,'planned',NOW())")->execute([$orderId,$rid,$dayNo,$date->format('Y-m-d'),$type,$sourceId,(int)$paid,$amount,$reason]);$dayId=(int)$this->db->lastInsertId();
  $w=$this->db->prepare("SELECT ew.* FROM evidence_windows ew JOIN order_days od ON od.id=ew.order_day_id WHERE od.order_id=? AND od.order_run_id=? AND od.day_type='regular' ORDER BY od.calendar_date DESC,ew.starts_at");$w->execute([$orderId,$rid]);$templates=[];foreach($w->fetchAll() as $row){$key=$row['name'];if(!isset($templates[$key]))$templates[$key]=$row;}
  foreach($templates as $row){$startParts=date('H:i:s',strtotime($row['starts_at']));$endParts=date('H:i:s',strtotime($row['ends_at']));$starts=$date->format('Y-m-d').' '.$startParts;$ends=$date->format('Y-m-d').' '.$endParts;$grace=(new DateTimeImmutable($ends))->modify('+1 hour')->format('Y-m-d H:i:s');$this->db->prepare("INSERT INTO evidence_windows(order_day_id,name,starts_at,ends_at,grace_ends_at,required_count,config_json,status,created_at) VALUES(?,?,?,?,?,?,?,'open',NOW())")->execute([$dayId,$row['name'],$starts,$ends,$grace,$row['required_count'],$row['config_json']]);}
 }
 public function sendChat(Request $r,array $p):void{$q=$this->db->prepare('SELECT id,is_readonly FROM chats WHERE order_id=?');$q->execute([(int)$p['id']]);$c=$q->fetch();if(!$c)Response::abort(404);$msg=trim((string)$r->input('message'));if($msg!==''&&!$c['is_readonly'])$this->db->prepare("INSERT INTO chat_messages(chat_id,sender_type,sender_id,message,created_at) VALUES(?,'admin',?,?,NOW())")->execute([$c['id'],$this->auth->admin()['id'],$msg]);Response::redirect('/admin/auftraege/'.$p['id']);}
}