<?php
namespace App\Http\Controllers;
use App\Core\Auth;use App\Core\Request;use App\Core\Response;use App\Core\Session;use App\Core\View;use PDO;
final class AdminSellerController{
 public function __construct(private string $root,private PDO $db,private Auth $auth){}
 public function index(Request $r):void{$q=trim((string)$r->input('q'));$sql='SELECT s.*,(SELECT COUNT(*) FROM orders o WHERE o.seller_id=s.id) order_count FROM sellers s WHERE 1';$params=[];if($q!==''){$sql.=" AND (s.first_name LIKE ? OR s.last_name LIKE ? OR s.email LIKE ? OR s.phone LIKE ?)";$like='%'.$q.'%';$params=[$like,$like,$like,$like];}$sql.=' ORDER BY s.created_at DESC LIMIT 250';$st=$this->db->prepare($sql);$st->execute($params);View::render($this->root,'admin/sellers',['pageTitle'=>'Verkäuferinnen','sellers'=>$st->fetchAll()]);}
 public function show(Request $r,array $p):void{
  $id=(int)$p['id'];$q=$this->db->prepare('SELECT * FROM sellers WHERE id=?');$q->execute([$id]);$s=$q->fetch();if(!$s)Response::abort(404);
  $orders=$this->db->prepare("SELECT o.*,ov.title,(SELECT COUNT(*) FROM order_offer_items ooi WHERE ooi.order_id=o.id) offer_count FROM orders o JOIN offer_versions ov ON ov.id=o.offer_version_id WHERE o.seller_id=? ORDER BY o.created_at DESC");$orders->execute([$id]);$orderRows=$orders->fetchAll();foreach($orderRows as &$orderRow){if((int)($orderRow['offer_count']??0)>1)$orderRow['title']='Sammelauftrag · '.(int)$orderRow['offer_count'].' Angebote';}unset($orderRow);$events=$this->db->prepare('SELECT * FROM system_events WHERE seller_id=? ORDER BY created_at DESC LIMIT 200');$events->execute([$id]);$changes=$this->db->prepare('SELECT * FROM seller_data_changes WHERE seller_id=? ORDER BY changed_at DESC LIMIT 200');$changes->execute([$id]);$wallet=$this->db->prepare('SELECT * FROM wallets WHERE seller_id=?');$wallet->execute([$id]);$payouts=$this->db->prepare('SELECT * FROM payout_requests WHERE seller_id=? ORDER BY requested_at DESC');$payouts->execute([$id]);$viol=$this->db->prepare('SELECT v.*,o.order_number FROM violations v JOIN orders o ON o.id=v.order_id WHERE o.seller_id=? ORDER BY v.created_at DESC');$viol->execute([$id]);
  View::render($this->root,'admin/seller',['pageTitle'=>'Verkäuferinnenakte','seller'=>$s,'orders'=>$orderRows,'events'=>$events->fetchAll(),'changes'=>$changes->fetchAll(),'wallet'=>$wallet->fetch(),'payouts'=>$payouts->fetchAll(),'violations'=>$viol->fetchAll()]);
 }
 public function update(Request $r,array $p):void{
  $id=(int)$p['id'];$q=$this->db->prepare('SELECT * FROM sellers WHERE id=?');$q->execute([$id]);$s=$q->fetch();if(!$s)Response::abort(404);
  $newEmail=mb_strtolower(trim((string)$r->input('email')));$newBirth=(string)$r->input('birth_date');$sensitive=$newEmail!==$s['email']||$newBirth!==$s['birth_date'];
  if($sensitive){$admin=$this->auth->admin();if(!password_verify((string)$r->input('admin_password'),$admin['password_hash'])){Session::flash('error','Für E-Mail/Geburtsdatum ist die Bestätigung mit dem Admin-Passwort erforderlich.');Response::redirect('/admin/verkaeuferinnen/'.$id);}}
  $values=['first_name'=>trim((string)$r->input('first_name')),'last_name'=>trim((string)$r->input('last_name')),'birth_date'=>$newBirth,'street'=>trim((string)$r->input('street')),'postal_code'=>trim((string)$r->input('postal_code')),'city'=>trim((string)$r->input('city')),'phone'=>trim((string)$r->input('phone')),'email'=>$newEmail];
  $this->db->beginTransaction();try{$changedFields=[];foreach($values as $f=>$v){if((string)$s[$f]===$v)continue;$changedFields[]=$f;$this->db->prepare('INSERT INTO seller_data_changes(seller_id,field_name,old_value,new_value,changed_at) VALUES(?,?,?,?,NOW())')->execute([$id,$f,(string)$s[$f],$v]);}$verify=($newEmail!==$s['email'])?',email_verified_at=NULL':'';$this->db->prepare("UPDATE sellers SET first_name=?,last_name=?,birth_date=?,street=?,postal_code=?,city=?,phone=?,email=?,updated_at=NOW()$verify WHERE id=?")->execute([$values['first_name'],$values['last_name'],$values['birth_date'],$values['street'],$values['postal_code'],$values['city'],$values['phone'],$values['email'],$id]);if($changedFields){$this->db->prepare("INSERT INTO system_events(seller_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,'seller_data_changed','admin',?,?,NOW())")->execute([$id,$this->auth->admin()['id'],json_encode(['fields'=>$changedFields],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}$this->db->commit();Session::flash('success',$changedFields?'Verkäuferinnendaten aktualisiert.':'Es wurden keine Änderungen vorgenommen.');}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}Response::redirect('/admin/verkaeuferinnen/'.$id);
 }
 public function delete(Request $r,array $p):void{
  $id=(int)$p['id'];$q=$this->db->prepare('SELECT * FROM sellers WHERE id=? AND deleted_at IS NULL');$q->execute([$id]);$s=$q->fetch();if(!$s)Response::abort(404);
  $this->db->beginTransaction();try{$anon='deleted+'.$id.'@invalid.local';$this->db->prepare("UPDATE sellers SET first_name='Gelöscht',last_name='Konto',birth_date='1900-01-01',street='anonymisiert',postal_code='00000',city='anonymisiert',phone='anonymisiert',email=?,email_verified_at=NULL,password_hash=?,updated_at=NOW(),deleted_at=NOW() WHERE id=?")->execute([$anon,password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT),$id]);$this->db->prepare('DELETE FROM payout_methods WHERE seller_id=?')->execute([$id]);$this->db->prepare('DELETE FROM email_verifications WHERE seller_id=?')->execute([$id]);$this->db->prepare('DELETE FROM password_resets WHERE seller_id=?')->execute([$id]);$this->db->prepare('DELETE FROM notifications WHERE seller_id=?')->execute([$id]);$this->db->prepare("INSERT INTO system_events(seller_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,'seller_anonymized','admin',?,'{}',NOW())")->execute([$id,$this->auth->admin()['id']]);$this->db->commit();Session::flash('success','Konto wurde gelöscht/anonymisiert. Historische Geschäfts- und Nachweisdaten bleiben erhalten.');}catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}Response::redirect('/admin/verkaeuferinnen/'.$id);
 }
}