<?php
namespace App\Http\Controllers;
use App\Core\Auth;use App\Core\Request;use App\Core\Response;use App\Core\Session;use App\Core\View;use App\Services\OrderService;use App\Services\PrivateStorage;use PDO;use RuntimeException;
final class OrderController{
 public function __construct(private string $root,private PDO $db,private Auth $auth){}
 public function acceptOffer(Request $r,array $p):void{
  $s=$this->auth->seller();try{$options=$r->input('options',[]);if(!is_array($options))$options=[];$id=(new OrderService($this->db))->accept((int)$s['id'],(int)$p['id'],$options,(bool)$r->input('rights_acceptance'));Session::flash('success','Auftrag wurde angenommen und für die Vorbereitung angelegt.');Response::redirect('/konto/auftraege/'.$id);}catch(\Throwable $e){Session::flash('error',$e->getMessage());Response::redirect('/angebote/'.$p['id']);}
 }
 public function show(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare("SELECT o.*,ov.title,ov.description,ov.duration_value,ov.duration_unit,ov.start_control_json,ov.evidence_json,c.name category_name,c.is_digital FROM orders o JOIN offer_versions ov ON ov.id=o.offer_version_id JOIN offers off ON off.id=o.offer_id JOIN categories c ON c.id=off.category_id WHERE o.id=? AND o.seller_id=?");$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);
  $run=$this->db->prepare('SELECT * FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$run=$run->fetch();
  $components=$this->db->prepare("SELECT oc.*,c.name category_name FROM order_components oc JOIN categories c ON c.id=oc.category_id WHERE oc.order_id=? ORDER BY oc.sort_order,oc.id");$components->execute([$o['id']]);$components=$components->fetchAll();
  $itemsQ=$this->db->prepare('SELECT * FROM order_items WHERE order_id=? AND order_run_id=? ORDER BY id');$itemsQ->execute([$o['id'],$run['id']]);$items=[];foreach($itemsQ->fetchAll() as $it)$items[(int)($it['order_component_id']??0)]=$it;$item=$items?reset($items):false;
  $preQ=$this->db->prepare("SELECT pr.*,oc.title component_title,(SELECT COUNT(*) FROM evidences e WHERE e.precheck_requirement_id=pr.id AND e.review_status='accepted') accepted_count,(SELECT COUNT(*) FROM evidences e WHERE e.precheck_requirement_id=pr.id AND e.review_status='pending') pending_count FROM precheck_requirements pr LEFT JOIN order_components oc ON oc.id=pr.order_component_id WHERE pr.order_id=? AND pr.order_run_id=? ORDER BY oc.sort_order,pr.sort_order,pr.id");$preQ->execute([$o['id'],$run['id']]);$precheckRequirements=$preQ->fetchAll();
  $ev=$this->db->prepare("SELECT e.*,ew.name window_name,pr.label precheck_label,oc.title component_title FROM evidences e LEFT JOIN evidence_windows ew ON ew.id=e.evidence_window_id LEFT JOIN precheck_requirements pr ON pr.id=e.precheck_requirement_id LEFT JOIN order_components oc ON oc.id=e.order_component_id WHERE e.order_id=? ORDER BY e.created_at DESC");$ev->execute([$o['id']]);
  $days=$this->db->prepare("SELECT od.*,oc.title component_title,(SELECT COUNT(*) FROM evidence_windows ew WHERE ew.order_day_id=od.id) window_count FROM order_days od LEFT JOIN order_components oc ON oc.id=od.order_component_id WHERE od.order_id=? ORDER BY calendar_date,oc.sort_order,COALESCE(day_no,0)");$days->execute([$o['id']]);
  $windows=$this->db->prepare("SELECT ew.*,od.day_no,od.calendar_date,od.order_component_id,oc.title component_title,(SELECT COUNT(*) FROM evidences e WHERE e.evidence_window_id=ew.id) uploaded_count FROM evidence_windows ew JOIN order_days od ON od.id=ew.order_day_id LEFT JOIN order_components oc ON oc.id=od.order_component_id WHERE od.order_id=? ORDER BY ew.starts_at,oc.sort_order");$windows->execute([$o['id']]);
  $viol=$this->db->prepare('SELECT * FROM violations WHERE order_id=? ORDER BY created_at DESC');$viol->execute([$o['id']]);
  $sp=$this->db->prepare("SELECT sr.*,(SELECT COUNT(*) FROM evidences e WHERE e.spontaneous_request_id=sr.id) uploaded_count FROM spontaneous_requests sr WHERE sr.order_id=? ORDER BY sr.created_at DESC");$sp->execute([$o['id']]);
  $tasks=$this->db->prepare("SELECT te.*,t.title,t.description,t.config_json FROM task_executions te JOIN tasks t ON t.id=te.task_id WHERE t.order_id=? ORDER BY te.due_at");$tasks->execute([$o['id']]);
  $damage=$this->db->prepare("SELECT dc.*,(SELECT COUNT(*) FROM damage_evidence_requests dr WHERE dr.damage_case_id=dc.id AND dr.status='requested') open_requests FROM damage_cases dc WHERE dc.order_id=? ORDER BY dc.created_at DESC");$damage->execute([$o['id']]);
  $damageReq=$this->db->prepare("SELECT dr.*,dc.order_id FROM damage_evidence_requests dr JOIN damage_cases dc ON dc.id=dr.damage_case_id WHERE dc.order_id=? ORDER BY dr.created_at DESC");$damageReq->execute([$o['id']]);
  $chat=$this->db->prepare('SELECT cm.* FROM chat_messages cm JOIN chats c ON c.id=cm.chat_id WHERE c.order_id=? ORDER BY cm.created_at');$chat->execute([$o['id']]);
  $shipping=$this->db->prepare("SELECT sw.*,ra.label,ra.recipient_name,ra.street,ra.postal_code,ra.city,ra.country_code,s.status shipment_status,s.tracking_number,s.shipped_at,s.received_at FROM shipping_workflows sw LEFT JOIN recipient_addresses ra ON ra.id=sw.recipient_address_id LEFT JOIN shipments s ON s.shipping_workflow_id=sw.id WHERE sw.order_id=?");$shipping->execute([$o['id']]);$shipping=$shipping->fetch();
  $shippingSteps=[];if($shipping){$ss=$this->db->prepare('SELECT * FROM shipping_steps WHERE shipping_workflow_id=? ORDER BY step_no');$ss->execute([$shipping['id']]);$shippingSteps=$ss->fetchAll();}
  $final=$this->db->prepare('SELECT decision,approved_amount,seller_message,decided_at FROM final_reviews WHERE order_id=?');$final->execute([$o['id']]);$final=$final->fetch();
  $digitalComponents=$this->db->prepare("SELECT dc.*,oc.title component_title FROM digital_components dc JOIN order_components oc ON oc.id=dc.order_component_id WHERE oc.order_id=? ORDER BY dc.id");$digitalComponents->execute([$o['id']]);$digitalComponents=$digitalComponents->fetchAll();
  $digitalVersions=[];$revisionRounds=[];$revisionItems=[];
  foreach($digitalComponents as $dc){
   $v=$this->db->prepare("SELECT dv.*,ds.status submission_status,ds.finalized_at FROM digital_versions dv JOIN digital_submissions ds ON ds.id=dv.digital_submission_id WHERE ds.digital_component_id=? ORDER BY dv.version_no DESC");$v->execute([$dc['id']]);$digitalVersions[$dc['id']]=$v->fetchAll();
   $rr=$this->db->prepare("SELECT * FROM revision_rounds WHERE digital_component_id=? ORDER BY round_no DESC");$rr->execute([$dc['id']]);$revisionRounds[$dc['id']]=$rr->fetchAll();
   foreach($revisionRounds[$dc['id']] as $round){$ri=$this->db->prepare('SELECT * FROM revision_items WHERE revision_round_id=? ORDER BY id');$ri->execute([$round['id']]);$revisionItems[$round['id']]=$ri->fetchAll();}
  }
  View::render($this->root,'seller/order',['pageTitle'=>'Auftrag #'.$o['order_number'],'order'=>$o,'run'=>$run,'item'=>$item,'items'=>$items,'components'=>$components,'precheckRequirements'=>$precheckRequirements,'evidences'=>$ev->fetchAll(),'days'=>$days->fetchAll(),'windows'=>$windows->fetchAll(),'violations'=>$viol->fetchAll(),'spontaneous'=>$sp->fetchAll(),'tasks'=>$tasks->fetchAll(),'damageCases'=>$damage->fetchAll(),'damageRequests'=>$damageReq->fetchAll(),'messages'=>$chat->fetchAll(),'shipping'=>$shipping,'shippingSteps'=>$shippingSteps,'finalReview'=>$final,'digitalComponents'=>$digitalComponents,'digitalVersions'=>$digitalVersions,'revisionRounds'=>$revisionRounds,'revisionItems'=>$revisionItems]);
 }
 public function saveItem(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare('SELECT * FROM orders WHERE id=? AND seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);if($o['started_at']){Session::flash('error','Nach Start der physischen Durchführung ist kein normaler Artikelwechsel mehr möglich.');Response::redirect('/konto/auftraege/'.$o['id']);}
  $componentId=(int)$r->input('order_component_id');$cq=$this->db->prepare("SELECT * FROM order_components WHERE id=? AND order_id=? AND component_type='physical'");$cq->execute([$componentId,$o['id']]);$component=$cq->fetch();if(!$component){Session::flash('error','Physischer Auftragsbestandteil wurde nicht gefunden.');Response::redirect('/konto/auftraege/'.$o['id']);}
  $run=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$rid=(int)$run->fetchColumn();
  $this->db->prepare('DELETE FROM order_items WHERE order_id=? AND order_run_id=? AND order_component_id=?')->execute([$o['id'],$rid,$componentId]);
  $this->db->prepare('INSERT INTO order_items(order_id,order_run_id,order_component_id,category_id,short_name,size,color,brand,material,attributes_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$o['id'],$rid,$componentId,$component['category_id'],trim((string)$r->input('short_name')),trim((string)$r->input('size'))?:null,trim((string)$r->input('color'))?:null,trim((string)$r->input('brand'))?:null,trim((string)$r->input('material'))?:null,'{}']);
  Session::flash('success','Artikelangaben für „'.$component['title'].'“ gespeichert.');Response::redirect('/konto/auftraege/'.$o['id']);
 }
 public function uploadEvidence(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare('SELECT * FROM orders WHERE id=? AND seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);
  try{
   $run=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$rid=(int)$run->fetchColumn();
   $type=(string)$r->input('evidence_type','regular');$windowId=$r->input('evidence_window_id')?(int)$r->input('evidence_window_id'):null;$componentId=null;$precheckRequirementId=null;
   if($type==='precheck'){
    if($o['started_at'])throw new RuntimeException('Vorabnachweise können nach Start nicht mehr ergänzt werden.');
    $precheckRequirementId=(int)$r->input('precheck_requirement_id');$pr=$this->db->prepare("SELECT pr.*,oc.id component_id FROM precheck_requirements pr JOIN order_components oc ON oc.id=pr.order_component_id WHERE pr.id=? AND pr.order_id=? AND pr.order_run_id=?");$pr->execute([$precheckRequirementId,$o['id'],$rid]);$req=$pr->fetch();if(!$req)throw new RuntimeException('Vorabanforderung ist ungültig.');$componentId=(int)$req['component_id'];
    $it=$this->db->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=? AND order_run_id=? AND order_component_id=?');$it->execute([$o['id'],$rid,$componentId]);if((int)$it->fetchColumn()<1)throw new RuntimeException('Bitte zuerst den konkreten Artikel dieses Bestandteils erfassen.');
   } else {
    if(!$windowId)throw new RuntimeException('Nachweisfenster fehlt.');$w=$this->db->prepare("SELECT ew.*,od.order_component_id FROM evidence_windows ew JOIN order_days od ON od.id=ew.order_day_id WHERE ew.id=? AND od.order_id=? AND od.order_run_id=? AND od.status<>'ended_by_restart'");$w->execute([$windowId,$o['id'],$rid]);$win=$w->fetch();if(!$win)throw new RuntimeException('Nachweisfenster ist ungültig oder gehört zu einem früheren Durchlauf.');$componentId=$win['order_component_id']?(int)$win['order_component_id']:null;$now=time();if($now<strtotime($win['starts_at']))throw new RuntimeException('Das Nachweisfenster hat noch nicht begonnen.');if($now>strtotime($win['grace_ends_at']))throw new RuntimeException('Die Nachfrist ist abgelaufen.');
   }
   $cfg=require $this->root.'/config/app.php';$file=(new PrivateStorage($cfg['private_storage']))->storeUploaded($r->files['evidence']??[],'evidence',['image/jpeg','image/png','image/webp'],12*1024*1024);
   $this->db->prepare("INSERT INTO evidences(order_id,order_run_id,order_component_id,precheck_requirement_id,evidence_window_id,evidence_type,file_path,original_name,mime_type,file_size,sha256,captured_at,metadata_json,review_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,NOW(),?,'pending',NOW())")->execute([$o['id'],$rid,$componentId,$precheckRequirementId,$windowId,$type,$file['path'],$file['original_name'],$file['mime'],$file['size'],$file['sha256'],json_encode(['user_agent'=>$r->server['HTTP_USER_AGENT']??null],JSON_UNESCAPED_UNICODE)]);
   Session::flash('success','Nachweis wurde unverändert gespeichert und zur Prüfung eingereicht.');
  }catch(\Throwable $e){Session::flash('error',$e->getMessage());}
  Response::redirect('/konto/auftraege/'.$o['id']);
 }
 public function sendChat(Request $r,array $p):void{$s=$this->auth->seller();$q=$this->db->prepare('SELECT c.id,c.is_readonly FROM chats c JOIN orders o ON o.id=c.order_id WHERE o.id=? AND o.seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$c=$q->fetch();if(!$c)Response::abort(404);if($c['is_readonly']){Session::flash('error','Dieser Chat ist schreibgeschützt.');Response::redirect('/konto/auftraege/'.$p['id']);}$msg=trim((string)$r->input('message'));if($msg!=='')$this->db->prepare("INSERT INTO chat_messages(chat_id,sender_type,sender_id,message,created_at) VALUES(?,'seller',?,?,NOW())")->execute([$c['id'],$s['id'],$msg]);Response::redirect('/konto/auftraege/'.$p['id']);}
}