<?php
namespace App\Http\Controllers;
use App\Core\Auth;use App\Core\Request;use App\Core\Response;use App\Core\Session;use App\Core\View;use App\Services\OrderService;use App\Services\PrivateStorage;use PDO;use RuntimeException;
final class OrderController{
 public function __construct(private string $root,private PDO $db,private Auth $auth){}
 public function acceptOffer(Request $r,array $p):void{
  $s=$this->auth->seller();try{if(!$r->input('summary_confirmation'))throw new RuntimeException('Bitte die Auftragszusammenfassung vor der Annahme bestätigen.');$options=$r->input('options',[]);if(!is_array($options))$options=[];$id=(new OrderService($this->db, $this->root))->accept((int)$s['id'],(int)$p['id'],$options,(bool)$r->input('rights_acceptance'));Session::flash('success','Auftrag wurde angenommen und für die Vorbereitung angelegt.');Response::redirect('/konto/auftraege/'.$id);}catch(\Throwable $e){Session::flash('error',$e->getMessage());Response::redirect('/angebote/'.$p['id']);}
 }
 public function show(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare("SELECT o.*,ov.title,ov.description,ov.duration_value,ov.duration_unit,ov.start_control_json,ov.evidence_json,c.name category_name,c.is_digital FROM orders o JOIN offer_versions ov ON ov.id=o.offer_version_id JOIN offers off ON off.id=o.offer_id JOIN categories c ON c.id=off.category_id WHERE o.id=? AND o.seller_id=?");$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);
  $run=$this->db->prepare('SELECT * FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$run=$run->fetch();
  $components=$this->db->prepare("SELECT oc.*,c.name category_name FROM order_components oc JOIN categories c ON c.id=oc.category_id WHERE oc.order_id=? ORDER BY oc.sort_order,oc.id");$components->execute([$o['id']]);$components=$components->fetchAll();
  $itemsQ=$this->db->prepare('SELECT * FROM order_items WHERE order_id=? AND order_run_id=? ORDER BY id');$itemsQ->execute([$o['id'],$run['id']]);$items=[];foreach($itemsQ->fetchAll() as $it)$items[(int)($it['order_component_id']??0)]=$it;$item=$items?reset($items):false;
  $preQ=$this->db->prepare("SELECT pr.*,oc.title component_title,(SELECT COUNT(*) FROM evidences e WHERE e.precheck_requirement_id=pr.id AND e.review_status='accepted') accepted_count,(SELECT COUNT(*) FROM evidences e WHERE e.precheck_requirement_id=pr.id AND e.review_status='pending') pending_count FROM precheck_requirements pr LEFT JOIN order_components oc ON oc.id=pr.order_component_id WHERE pr.order_id=? AND pr.order_run_id=? ORDER BY oc.sort_order,pr.sort_order,pr.id");$preQ->execute([$o['id'],$run['id']]);$precheckRequirements=$preQ->fetchAll();
  $ev=$this->db->prepare("SELECT e.*,ew.name window_name,pr.label precheck_label,oc.title component_title FROM evidences e LEFT JOIN evidence_windows ew ON ew.id=e.evidence_window_id LEFT JOIN precheck_requirements pr ON pr.id=e.precheck_requirement_id LEFT JOIN order_components oc ON oc.id=e.order_component_id WHERE e.order_id=? ORDER BY e.created_at DESC");$ev->execute([$o['id']]);
  $days=$this->db->prepare("SELECT od.*,oc.title component_title,(SELECT COUNT(*) FROM evidence_windows ew WHERE ew.order_day_id=od.id) window_count FROM order_days od LEFT JOIN order_components oc ON oc.id=od.order_component_id WHERE od.order_id=? ORDER BY calendar_date,oc.sort_order,COALESCE(day_no,0)");$days->execute([$o['id']]);
  $windows=$this->db->prepare("SELECT ew.*,od.day_no,od.calendar_date,od.order_component_id,oc.title component_title,(SELECT COUNT(*) FROM evidences e WHERE e.evidence_window_id=ew.id) uploaded_count FROM evidence_windows ew JOIN order_days od ON od.id=ew.order_day_id LEFT JOIN order_components oc ON oc.id=od.order_component_id WHERE od.order_id=? ORDER BY ew.starts_at,oc.sort_order");$windows->execute([$o['id']]);
  $viol=$this->db->prepare('SELECT * FROM violations WHERE order_id=? ORDER BY created_at DESC');$viol->execute([$o['id']]);
  $sp=$this->db->prepare("SELECT sr.*,oc.title component_title,(SELECT COUNT(*) FROM evidences e WHERE e.spontaneous_request_id=sr.id) uploaded_count FROM spontaneous_requests sr LEFT JOIN order_components oc ON oc.id=sr.order_component_id WHERE sr.order_id=? ORDER BY sr.created_at DESC");$sp->execute([$o['id']]);
  $tasks=$this->db->prepare("SELECT te.*,t.title,t.description,t.config_json,oc.title component_title FROM task_executions te JOIN tasks t ON t.id=te.task_id LEFT JOIN order_components oc ON oc.id=t.order_component_id WHERE t.order_id=? ORDER BY te.due_at");$tasks->execute([$o['id']]);
  $damage=$this->db->prepare("SELECT dc.*,oc.title component_title,(SELECT COUNT(*) FROM damage_evidence_requests dr WHERE dr.damage_case_id=dc.id AND dr.status='requested') open_requests FROM damage_cases dc LEFT JOIN order_components oc ON oc.id=dc.order_component_id WHERE dc.order_id=? ORDER BY dc.created_at DESC");$damage->execute([$o['id']]);
  $damageReq=$this->db->prepare("SELECT dr.*,dc.order_id FROM damage_evidence_requests dr JOIN damage_cases dc ON dc.id=dr.damage_case_id WHERE dc.order_id=? ORDER BY dr.created_at DESC");$damageReq->execute([$o['id']]);
  $chatInfoQ=$this->db->prepare('SELECT id,is_readonly FROM chats WHERE order_id=?');$chatInfoQ->execute([$o['id']]);$chatInfo=$chatInfoQ->fetch();$chatReadonly=$chatInfo?(bool)$chatInfo['is_readonly']:true;
  $chat=$this->db->prepare('SELECT * FROM chat_messages WHERE chat_id=? ORDER BY created_at');$chat->execute([$chatInfo['id']??0]);
  $shipping=$this->db->prepare("SELECT sw.*,ra.label,ra.recipient_name,ra.street,ra.postal_code,ra.city,ra.country_code,s.status shipment_status,s.tracking_number,s.shipped_at,s.received_at FROM shipping_workflows sw LEFT JOIN recipient_addresses ra ON ra.id=sw.recipient_address_id LEFT JOIN shipments s ON s.shipping_workflow_id=sw.id WHERE sw.order_id=?");$shipping->execute([$o['id']]);$shipping=$shipping->fetch();
  $shippingSteps=[];if($shipping){$ss=$this->db->prepare('SELECT * FROM shipping_steps WHERE shipping_workflow_id=? ORDER BY step_no');$ss->execute([$shipping['id']]);$shippingSteps=$ss->fetchAll();}
  $final=$this->db->prepare('SELECT decision,approved_amount,seller_message,decided_at FROM final_reviews WHERE order_id=?');$final->execute([$o['id']]);$final=$final->fetch();
  $orderOptionsQ=$this->db->prepare('SELECT * FROM order_options WHERE order_id=? AND is_active=1 ORDER BY id');$orderOptionsQ->execute([$o['id']]);$orderOptions=$orderOptionsQ->fetchAll();
  $offerOptionsQ=$this->db->prepare("SELECT * FROM offer_options WHERE offer_version_id=? AND is_active=1 ORDER BY sort_order,id");$offerOptionsQ->execute([$o['offer_version_id']]);$offerOptions=$offerOptionsQ->fetchAll();
  $adjustQ=$this->db->prepare("SELECT * FROM order_adjustments WHERE order_id=? AND status<>'cancelled' ORDER BY created_at,id");$adjustQ->execute([$o['id']]);$adjustments=$adjustQ->fetchAll();
  $manualQ=$this->db->prepare('SELECT med.*,oc.title component_title FROM manual_extra_days med LEFT JOIN order_components oc ON oc.id=med.order_component_id WHERE med.order_id=? ORDER BY med.created_at,med.id');$manualQ->execute([$o['id']]);$manualExtraDays=$manualQ->fetchAll();
  $digitalComponents=$this->db->prepare("SELECT dc.*,oc.title component_title FROM digital_components dc JOIN order_components oc ON oc.id=dc.order_component_id WHERE oc.order_id=? ORDER BY dc.id");$digitalComponents->execute([$o['id']]);$digitalComponents=$digitalComponents->fetchAll();
  $digitalVersions=[];$revisionRounds=[];$revisionItems=[];
  foreach($digitalComponents as $dc){
   $v=$this->db->prepare("SELECT dv.*,ds.status submission_status,ds.finalized_at FROM digital_versions dv JOIN digital_submissions ds ON ds.id=dv.digital_submission_id WHERE ds.digital_component_id=? ORDER BY dv.version_no DESC");$v->execute([$dc['id']]);$digitalVersions[$dc['id']]=$v->fetchAll();
   $rr=$this->db->prepare("SELECT * FROM revision_rounds WHERE digital_component_id=? ORDER BY round_no DESC");$rr->execute([$dc['id']]);$revisionRounds[$dc['id']]=$rr->fetchAll();
   foreach($revisionRounds[$dc['id']] as $round){$ri=$this->db->prepare('SELECT * FROM revision_items WHERE revision_round_id=? ORDER BY id');$ri->execute([$round['id']]);$revisionItems[$round['id']]=$ri->fetchAll();}
  }
  View::render($this->root,'seller/order',['pageTitle'=>'Auftrag #'.$o['order_number'],'order'=>$o,'run'=>$run,'item'=>$item,'items'=>$items,'components'=>$components,'precheckRequirements'=>$precheckRequirements,'evidences'=>$ev->fetchAll(),'days'=>$days->fetchAll(),'windows'=>$windows->fetchAll(),'violations'=>$viol->fetchAll(),'spontaneous'=>$sp->fetchAll(),'tasks'=>$tasks->fetchAll(),'damageCases'=>$damage->fetchAll(),'damageRequests'=>$damageReq->fetchAll(),'messages'=>$chat->fetchAll(),'shipping'=>$shipping,'shippingSteps'=>$shippingSteps,'finalReview'=>$final,'orderOptions'=>$orderOptions,'offerOptions'=>$offerOptions,'adjustments'=>$adjustments,'manualExtraDays'=>$manualExtraDays,'digitalComponents'=>$digitalComponents,'digitalVersions'=>$digitalVersions,'revisionRounds'=>$revisionRounds,'revisionItems'=>$revisionItems,'chatReadonly'=>$chatReadonly]);
 }
 public function saveItem(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare('SELECT * FROM orders WHERE id=? AND seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);if($o['started_at']){Session::flash('error','Nach Start der physischen Durchführung ist kein normaler Artikelwechsel mehr möglich.');Response::redirect('/konto/auftraege/'.$o['id']);}
  $componentId=(int)$r->input('order_component_id');$cq=$this->db->prepare("SELECT * FROM order_components WHERE id=? AND order_id=? AND component_type='physical'");$cq->execute([$componentId,$o['id']]);$component=$cq->fetch();if(!$component){Session::flash('error','Physischer Auftragsbestandteil wurde nicht gefunden.');Response::redirect('/konto/auftraege/'.$o['id']);}
  $run=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$rid=(int)$run->fetchColumn();
  $this->db->prepare('DELETE FROM order_items WHERE order_id=? AND order_run_id=? AND order_component_id=?')->execute([$o['id'],$rid,$componentId]);
  $this->db->prepare('INSERT INTO order_items(order_id,order_run_id,order_component_id,category_id,short_name,size,color,brand,material,attributes_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$o['id'],$rid,$componentId,$component['category_id'],trim((string)$r->input('short_name')),trim((string)$r->input('size'))?:null,trim((string)$r->input('color'))?:null,trim((string)$r->input('brand'))?:null,trim((string)$r->input('material'))?:null,'{}']);
  Session::flash('success','Artikelangaben für „'.$component['title'].'“ gespeichert.');Response::redirect('/konto/auftraege/'.$o['id']);
 }
 public function uploadEvidence(Request $r,array $p):void{
  $s=$this->auth->seller();$q=$this->db->prepare('SELECT * FROM orders WHERE id=? AND seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$o=$q->fetch();if(!$o)Response::abort(404);
  try{
   $run=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$run->execute([$o['id']]);$rid=(int)$run->fetchColumn();
   $type=(string)$r->input('evidence_type','regular');$windowId=$r->input('evidence_window_id')?(int)$r->input('evidence_window_id'):null;$componentId=null;$precheckRequirementId=null;
   if($type==='precheck'){
    if($o['started_at'])throw new RuntimeException('Vorabnachweise können nach Start nicht mehr ergänzt werden.');
    $precheckRequirementId=(int)$r->input('precheck_requirement_id');$pr=$this->db->prepare("SELECT pr.*,oc.id component_id FROM precheck_requirements pr JOIN order_components oc ON oc.id=pr.order_component_id WHERE pr.id=? AND pr.order_id=? AND pr.order_run_id=?");$pr->execute([$precheckRequirementId,$o['id'],$rid]);$req=$pr->fetch();if(!$req)throw new RuntimeException('Vorabanforderung ist ungültig.');$componentId=(int)$req['component_id'];
    $it=$this->db->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=? AND order_run_id=? AND order_component_id=?');$it->execute([$o['id'],$rid,$componentId]);if((int)$it->fetchColumn()<1)throw new RuntimeException('Bitte zuerst den konkreten Artikel dieses Bestandteils erfassen.');
   } else {
    if(!$windowId)throw new RuntimeException('Nachweisfenster fehlt.');$w=$this->db->prepare("SELECT ew.*,od.order_component_id FROM evidence_windows ew JOIN order_days od ON od.id=ew.order_day_id WHERE ew.id=? AND od.order_id=? AND od.order_run_id=? AND od.status<>'ended_by_restart'");$w->execute([$windowId,$o['id'],$rid]);$win=$w->fetch();if(!$win)throw new RuntimeException('Nachweisfenster ist ungültig oder gehört zu einem früheren Durchlauf.');$componentId=$win['order_component_id']?(int)$win['order_component_id']:null;$now=time();if($now<strtotime($win['starts_at']))throw new RuntimeException('Das Nachweisfenster hat noch nicht begonnen.');if($now>strtotime($win['grace_ends_at']))throw new RuntimeException('Die Nachfrist ist abgelaufen.');
   }
   $retakeOf=null;if($type==='precheck'&&$precheckRequirementId){$rq=$this->db->prepare("SELECT id FROM evidences WHERE order_id=? AND order_run_id=? AND precheck_requirement_id=? AND review_status='rejected' AND resolved_by_evidence_id IS NULL ORDER BY id DESC LIMIT 1");$rq->execute([$o['id'],$rid,$precheckRequirementId]);$retakeOf=$rq->fetchColumn()?:null;}
   $cfg=require $this->root.'/config/app.php';$file=(new PrivateStorage($cfg['private_storage']))->storeUploaded($r->files['evidence']??[],'evidence',['image/jpeg','image/png','image/webp'],12*1024*1024);
   $this->db->prepare("INSERT INTO evidences(order_id,order_run_id,order_component_id,precheck_requirement_id,retake_of_evidence_id,evidence_window_id,evidence_type,file_path,original_name,mime_type,file_size,sha256,captured_at,metadata_json,review_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,'pending',NOW())")->execute([$o['id'],$rid,$componentId,$precheckRequirementId,$retakeOf,$windowId,$type,$file['path'],$file['original_name'],$file['mime'],$file['size'],$file['sha256'],json_encode(['user_agent'=>$r->server['HTTP_USER_AGENT']??null],JSON_UNESCAPED_UNICODE)]);
   $newEvidenceId=(int)$this->db->lastInsertId();if($retakeOf)$this->db->prepare('UPDATE evidences SET resolved_by_evidence_id=? WHERE id=? AND resolved_by_evidence_id IS NULL')->execute([$newEvidenceId,$retakeOf]);
   Session::flash('success',$retakeOf?'Nachaufnahme wurde unverändert gespeichert und erneut zur Prüfung eingereicht.':'Nachweis wurde unverändert gespeichert und zur Prüfung eingereicht.');
  }catch(\Throwable $e){Session::flash('error',$e->getMessage());}
  Response::redirect('/konto/auftraege/'.$o['id']);
 }
 public function updateOptions(Request $r,array $p):void{
  $seller=$this->auth->seller();$orderId=(int)$p['id'];$selected=$r->input('options',[]);if(!is_array($selected))$selected=[];$selected=array_values(array_unique(array_map('intval',$selected)));
  $this->db->beginTransaction();try{
   $oq=$this->db->prepare('SELECT * FROM orders WHERE id=? AND seller_id=? FOR UPDATE');$oq->execute([$orderId,$seller['id']]);$order=$oq->fetch();if(!$order)Response::abort(404);
   if($order['started_at']||$order['phase']!=='preparation')throw new RuntimeException('Optionen können durch die Verkäuferin nur vor dem Auftragsstart geändert werden.');
   $availableQ=$this->db->prepare("SELECT * FROM offer_options WHERE offer_version_id=? AND is_active=1 ORDER BY id");$availableQ->execute([$order['offer_version_id']]);$available=$availableQ->fetchAll();$catalog=[];foreach($available as $op)$catalog[(int)$op['id']]=$op;
   foreach($selected as $id)if(!isset($catalog[$id]))throw new RuntimeException('Mindestens eine ausgewählte Option ist nicht verfügbar.');
   $currentQ=$this->db->prepare('SELECT * FROM order_options WHERE order_id=? AND is_active=1 FOR UPDATE');$currentQ->execute([$orderId]);$current=$currentQ->fetchAll();$currentByOffer=[];foreach($current as $op)$currentByOffer[(int)$op['offer_option_id']]=$op;
   $oldTotal=array_sum(array_map(fn($x)=>(float)$x['price'],$current));$newTotal=0.0;foreach($selected as $id)$newTotal+=(float)$catalog[$id]['price'];$delta=round($newTotal-$oldTotal,2);
   $walletQ=$this->db->prepare('SELECT * FROM wallets WHERE seller_id=? FOR UPDATE');$walletQ->execute([$seller['id']]);$wallet=$walletQ->fetch();if(!$wallet)throw new RuntimeException('Wallet nicht gefunden.');if((float)$wallet['balance_reserved']+$delta<0)throw new RuntimeException('Die Wallet-Reservierung kann nicht negativ werden.');
   foreach($currentByOffer as $offerOptionId=>$op){if(in_array($offerOptionId,$selected,true))continue;$this->db->prepare('UPDATE order_options SET is_active=0,removed_at=NOW() WHERE id=?')->execute([$op['id']]);$this->db->prepare("INSERT INTO order_adjustments(order_id,adjustment_type,label,amount,status,metadata_json,created_at) VALUES(?,'option_remove',?,?,'active',?,NOW())")->execute([$orderId,'Option vor Start entfernt: '.$op['name'],-(float)$op['price'],json_encode(['order_option_id'=>$op['id'],'actor'=>'seller'],JSON_UNESCAPED_UNICODE)]);}
   foreach($selected as $offerOptionId){if(isset($currentByOffer[$offerOptionId]))continue;$op=$catalog[$offerOptionId];$this->db->prepare('INSERT INTO order_options(order_id,offer_option_id,name,price,config_snapshot,is_active,created_at) VALUES(?,?,?,?,?,1,NOW())')->execute([$orderId,$offerOptionId,$op['name'],$op['price'],$op['requirements_json']]);$orderOptionId=(int)$this->db->lastInsertId();$this->db->prepare("INSERT INTO order_adjustments(order_id,adjustment_type,label,amount,status,metadata_json,created_at) VALUES(?,'option_add',?,?,'active',?,NOW())")->execute([$orderId,'Option vor Start hinzugefügt: '.$op['name'],(float)$op['price'],json_encode(['order_option_id'=>$orderOptionId,'actor'=>'seller'],JSON_UNESCAPED_UNICODE)]);}
   if($delta!=0.0){$this->db->prepare('UPDATE orders SET current_total=current_total+?,updated_at=NOW() WHERE id=?')->execute([$delta,$orderId]);$this->db->prepare('UPDATE wallets SET balance_reserved=balance_reserved+?,updated_at=NOW() WHERE id=?')->execute([$delta,$wallet['id']]);$this->db->prepare("INSERT INTO wallet_entries(wallet_id,order_id,entry_type,status,amount,metadata_json,created_at) VALUES(?,?,'option_change','reserved',?,?,NOW())")->execute([$wallet['id'],$orderId,$delta,json_encode(['actor'=>'seller','before'=>$oldTotal,'after'=>$newTotal],JSON_UNESCAPED_UNICODE)]);}
   $this->db->prepare("INSERT INTO system_events(seller_id,order_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,?,'options_changed','seller',?,?,NOW())")->execute([$seller['id'],$orderId,$seller['id'],json_encode(['selected'=>$selected,'delta'=>$delta],JSON_UNESCAPED_UNICODE)]);
   $this->db->commit();Session::flash('success','Optionsauswahl wurde aktualisiert.');
  }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();Session::flash('error',$e->getMessage());}
  Response::redirect('/konto/auftraege/'.$orderId);
 }
 public function sendChat(Request $r,array $p):void{$s=$this->auth->seller();$q=$this->db->prepare('SELECT c.id,c.is_readonly FROM chats c JOIN orders o ON o.id=c.order_id WHERE o.id=? AND o.seller_id=?');$q->execute([(int)$p['id'],$s['id']]);$c=$q->fetch();if(!$c)Response::abort(404);if($c['is_readonly']){Session::flash('error','Dieser Chat ist schreibgeschützt.');Response::redirect('/konto/auftraege/'.$p['id']);}$msg=trim((string)$r->input('message'));if($msg!=='')$this->db->prepare("INSERT INTO chat_messages(chat_id,sender_type,sender_id,message,created_at) VALUES(?,'seller',?,?,NOW())")->execute([$c['id'],$s['id'],$msg]);Response::redirect('/konto/auftraege/'.$p['id']);}
}