<?php
namespace App\Services;
use PDO;use RuntimeException;use DateTimeImmutable;use DateTimeZone;
final class OrderService{
 public function __construct(private PDO $db){}
 public function accept(int $sellerId,int $offerId,array $optionIds=[],bool $rightsAccepted=false):int{
  $this->db->beginTransaction();
  try{
   $q=$this->db->prepare("SELECT o.id offer_id,o.seller_id private_seller_id,o.is_private,o.acceptance_deadline,o.title offer_title,ov.id version_id,ov.title,ov.description,ov.compensation,ov.fulfillment_model,ov.duration_value,ov.duration_unit,ov.rules_json,ov.evidence_json,ov.start_control_json,ov.shipping_json,ov.end_workflow_json,ov.violation_json,c.id category_id,c.is_digital FROM offers o JOIN offer_versions ov ON ov.id=o.current_version_id JOIN categories c ON c.id=o.category_id WHERE o.id=? AND o.status='active' FOR UPDATE");$q->execute([$offerId]);$o=$q->fetch();
   if(!$o)throw new RuntimeException('Angebot ist nicht mehr verfügbar.');
   if((int)$o['is_private']===1&&(int)$o['private_seller_id']!==$sellerId)throw new RuntimeException('Dieses Angebot ist nicht für dein Konto bestimmt.');
   if($o['acceptance_deadline']&&strtotime($o['acceptance_deadline'])<time())throw new RuntimeException('Die Annahmefrist ist abgelaufen.');
   $b=$this->db->prepare("SELECT ord.order_number FROM orders ord JOIN order_components oc ON oc.order_id=ord.id WHERE ord.seller_id=? AND oc.category_id=? AND ord.status NOT IN('rejected','cancelled','paid','archived') LIMIT 1 FOR UPDATE");$b->execute([$sellerId,$o['category_id']]);if($b->fetch())throw new RuntimeException('In dieser Kategorie besteht bereits ein aktiver Auftrag.');
   if((int)$o['is_digital']===1&&!$rightsAccepted)throw new RuntimeException('Die Rechtevereinbarung muss vor Annahme bestätigt werden.');
   $selected=[];$optionsTotal=0.0;if($optionIds){$marks=implode(',',array_fill(0,count($optionIds),'?'));$op=$this->db->prepare("SELECT * FROM offer_options WHERE offer_version_id=? AND is_active=1 AND id IN($marks)");$op->execute(array_merge([$o['version_id']],array_map('intval',$optionIds)));$selected=$op->fetchAll();foreach($selected as $x)$optionsTotal+=(float)$x['price'];}
   $number=(new OrderNumberService($this->db))->next();$total=(float)$o['compensation']+$optionsTotal;
   $snapshot=json_encode(['offer_version_id'=>(int)$o['version_id'],'title'=>$o['title'],'description'=>$o['description'],'compensation'=>(float)$o['compensation'],'fulfillment_model'=>$o['fulfillment_model'],'duration_value'=>$o['duration_value'],'duration_unit'=>$o['duration_unit'],'rules'=>json_decode($o['rules_json']?:'[]',true),'evidence'=>json_decode($o['evidence_json']?:'[]',true),'start_control'=>json_decode($o['start_control_json']?:'[]',true),'shipping'=>json_decode($o['shipping_json']?:'[]',true),'end_workflow'=>json_decode($o['end_workflow_json']?:'[]',true),'violation'=>json_decode($o['violation_json']?:'[]',true)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
   $i=$this->db->prepare("INSERT INTO orders(order_number,seller_id,offer_id,offer_version_id,status,phase,accepted_at,base_compensation,current_total,config_snapshot,created_at,updated_at) VALUES(?,?,?,?, 'precheck','preparation',NOW(),?,?,?,NOW(),NOW())");$i->execute([$number,$sellerId,$offerId,$o['version_id'],$o['compensation'],$total,$snapshot]);$orderId=(int)$this->db->lastInsertId();
   $this->db->prepare("INSERT INTO order_components(order_id,category_id,component_type,title,compensation,status,config_json,created_at,updated_at) VALUES(?,?,?,?,?,'preparation',?,NOW(),NOW())")->execute([$orderId,$o['category_id'],(int)$o['is_digital']?'digital':'physical',$o['title'],$o['compensation'],$snapshot]);
   $this->db->prepare("INSERT INTO order_runs(order_id,run_no,status,created_at) VALUES(?,1,'preparation',NOW())")->execute([$orderId]);
   foreach($selected as $x)$this->db->prepare('INSERT INTO order_options(order_id,offer_option_id,name,price,config_snapshot,created_at) VALUES(?,?,?,?,?,NOW())')->execute([$orderId,$x['id'],$x['name'],$x['price'],$x['requirements_json']]);
   if((int)$o['is_digital']===1)$this->db->prepare('INSERT INTO rights_acceptances(order_id,seller_id,clause_version,accepted_at) VALUES(?,?,?,NOW())')->execute([$orderId,$sellerId,'2026-09-20']);
   $w=$this->db->prepare('SELECT id FROM wallets WHERE seller_id=? FOR UPDATE');$w->execute([$sellerId]);$walletId=(int)$w->fetchColumn();$this->db->prepare('UPDATE wallets SET balance_reserved=balance_reserved+?,updated_at=NOW() WHERE id=?')->execute([$total,$walletId]);$this->db->prepare("INSERT INTO wallet_entries(wallet_id,order_id,entry_type,status,amount,created_at) VALUES(?,?,'order_reservation','reserved',?,NOW())")->execute([$walletId,$orderId,$total]);
   $this->db->prepare('INSERT INTO chats(order_id,is_readonly,created_at) VALUES(?,0,NOW())')->execute([$orderId]);$chat=(int)$this->db->lastInsertId();$this->db->prepare("INSERT INTO chat_messages(chat_id,sender_type,message,created_at) VALUES(?,'system',?,NOW())")->execute([$chat,'Auftrag #'.$number.' wurde angenommen.']);
   $this->db->prepare("INSERT INTO system_events(seller_id,order_id,event_type,actor_type,actor_id,payload_json,created_at) VALUES(?,?,'order_accepted','seller',?,?,NOW())")->execute([$sellerId,$orderId,$sellerId,json_encode(['order_number'=>$number,'total'=>$total])]);
   $this->db->commit();return $orderId;
  }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
 public function startAfterPrecheck(int $orderId):void{
  $this->db->beginTransaction();try{
   $q=$this->db->prepare("SELECT o.*,ov.duration_value,ov.fulfillment_model,ov.evidence_json,c.is_digital FROM orders o JOIN offer_versions ov ON ov.id=o.offer_version_id JOIN offers off ON off.id=o.offer_id JOIN categories c ON c.id=off.category_id WHERE o.id=? FOR UPDATE");$q->execute([$orderId]);$o=$q->fetch();if(!$o)throw new RuntimeException('Auftrag nicht gefunden.');if($o['started_at'])throw new RuntimeException('Auftrag ist bereits gestartet.');
   $currentRun=$this->db->prepare('SELECT id FROM order_runs WHERE order_id=? ORDER BY run_no DESC LIMIT 1');$currentRun->execute([$orderId]);$currentRunId=(int)$currentRun->fetchColumn();
   $p=$this->db->prepare("SELECT COUNT(*) FROM evidences WHERE order_id=? AND order_run_id=? AND evidence_type='precheck'");$p->execute([$orderId,$currentRunId]);if((int)$p->fetchColumn()<1)throw new RuntimeException('Es liegt für den aktuellen Durchlauf noch kein Vorabnachweis vor.');
   $pending=$this->db->prepare("SELECT COUNT(*) FROM evidences WHERE order_id=? AND order_run_id=? AND evidence_type='precheck' AND review_status<>'accepted'");$pending->execute([$orderId,$currentRunId]);if((int)$pending->fetchColumn()>0)throw new RuntimeException('Nicht alle Pflichtaufnahmen des aktuellen Durchlaufs sind akzeptiert.');
   $item=$this->db->prepare('SELECT COUNT(*) FROM order_items WHERE order_id=? AND order_run_id=?');$item->execute([$orderId,$currentRunId]);if((int)$item->fetchColumn()<1)throw new RuntimeException('Für den aktuellen Durchlauf wurde noch kein Artikel festgelegt.');
   $now=new DateTimeImmutable('now',new DateTimeZone('Europe/Berlin'));$startDate=$now->setTime(0,0);$evidence=json_decode($o['evidence_json']?:'[]',true)?:[];$windows=$evidence['windows']??[['name'=>'Morgen','start'=>'06:00','end'=>'10:00','required_count'=>1],['name'=>'Mittag','start'=>'12:00','end'=>'16:00','required_count'=>1],['name'=>'Abend','start'=>'18:00','end'=>'23:59','required_count'=>1]];
   $future=false;foreach($windows as $w){[$h,$m]=array_map('intval',explode(':',$w['start']));if($startDate->setTime($h,$m)>$now){$future=true;break;}}
   $this->db->prepare("UPDATE orders SET status='running',phase='execution',started_at=NOW(),updated_at=NOW() WHERE id=?")->execute([$orderId]);$runId=$currentRunId;$this->db->prepare("UPDATE order_runs SET status='running',started_at=NOW() WHERE id=?")->execute([$runId]);
   if(!(int)$o['is_digital']&&$o['fulfillment_model']==='days'){$first=$future?$startDate:$startDate->modify('+1 day');if(!$future)$this->db->prepare("INSERT INTO order_days(order_id,order_run_id,day_no,calendar_date,day_type,status,created_at) VALUES(?,?,NULL,?,'start','active',NOW())")->execute([$orderId,$runId,$startDate->format('Y-m-d')]);$days=max(1,(int)$o['duration_value']);for($n=1;$n<=$days;$n++){$d=$first->modify('+'.($n-1).' day');$this->db->prepare("INSERT INTO order_days(order_id,order_run_id,day_no,calendar_date,day_type,status,created_at) VALUES(?,?,?,?, 'regular','planned',NOW())")->execute([$orderId,$runId,$n,$d->format('Y-m-d')]);$dayId=(int)$this->db->lastInsertId();foreach($windows as $w){[$sh,$sm]=array_map('intval',explode(':',$w['start']));[$eh,$em]=array_map('intval',explode(':',$w['end']));$from=$d->setTime($sh,$sm);$to=$d->setTime($eh,$em);$this->db->prepare("INSERT INTO evidence_windows(order_day_id,name,starts_at,ends_at,grace_ends_at,required_count,config_json,status,created_at) VALUES(?,?,?,?,?,?,?,'open',NOW())")->execute([$dayId,$w['name'],$from->format('Y-m-d H:i:s'),$to->format('Y-m-d H:i:s'),$to->modify('+1 hour')->format('Y-m-d H:i:s'),(int)($w['required_count']??1),json_encode($w,JSON_UNESCAPED_UNICODE)]);}}}
   $chat=$this->db->prepare('SELECT id FROM chats WHERE order_id=?');$chat->execute([$orderId]);if($cid=$chat->fetchColumn())$this->db->prepare("INSERT INTO chat_messages(chat_id,sender_type,message,created_at) VALUES(?,'system','Der Auftrag wurde nach Freigabe der Vorabkontrolle gestartet.',NOW())")->execute([$cid]);$this->db->prepare("INSERT INTO system_events(seller_id,order_id,event_type,actor_type,payload_json,created_at) SELECT seller_id,id,'order_started','admin','{}',NOW() FROM orders WHERE id=?")->execute([$orderId]);$this->db->commit();
  }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
 }
}