<main class="section">
<div class="seller-hero"><div><span class="eyebrow">Postfach</span><h1>Benachrichtigungen</h1><p>Neue Anforderungen, Fristen, Entscheidungen und Auszahlungen – chronologisch an einem Ort.</p></div><?php if($unreadCount>0):?><form method="post" action="/konto/benachrichtigungen/alle-gelesen"><?=App\Core\Csrf::field()?><button class="btn ghost">Alle als gelesen markieren</button></form><?php endif;?></div>

<div class="row-actions seller-section-card"><a class="btn <?=$filterMode==='all'?'primary':'ghost'?>" href="/konto/benachrichtigungen?filter=all">Alle</a><a class="btn <?=$filterMode==='unread'?'primary':'ghost'?>" href="/konto/benachrichtigungen?filter=unread">Ungelesen<?php if($unreadCount):?> · <?=$unreadCount?><?php endif;?></a></div>

<div class="card seller-section-card">
<?php foreach($notifications as $n):?><div class="seller-notification <?=empty($n['read_at'])?'unread':''?>"><div><div class="row-actions"><b><?=App\Core\View::e($n['title'])?></b><?php if(empty($n['read_at'])):?><span class="seller-status warn">Neu</span><?php endif;?></div><p><?=App\Core\View::e($n['message'])?></p><time><?=date('d.m.Y H:i',strtotime($n['created_at']))?></time></div><div class="actions"><?php if($n['url']):?><form method="post" action="/konto/benachrichtigungen/<?=$n['id']?>/gelesen"><?=App\Core\Csrf::field()?><input type="hidden" name="redirect" value="<?=App\Core\View::e($n['url'])?>"><button class="btn primary">Öffnen</button></form><?php endif;?><?php if(empty($n['read_at'])):?><form method="post" action="/konto/benachrichtigungen/<?=$n['id']?>/gelesen"><?=App\Core\Csrf::field()?><button class="btn ghost">Gelesen</button></form><?php endif;?></div></div><?php endforeach;?>
<?php if(!$notifications):?><div class="empty"><?=$filterMode==='unread'?'Keine ungelesenen Benachrichtigungen.':'Keine Benachrichtigungen vorhanden.'?></div><?php endif;?>
</div>
</main>