<?php $physicalComponents=array_values(array_filter($components,fn($x)=>$x['component_type']==='physical'));?>
<main class="section"><div class="section-head"><div><span class="eyebrow">Auftrag #<?=App\Core\View::e($order['order_number'])?></span><h1><?=App\Core\View::e($order['title'])?></h1><p class="muted"><?=count($components)>1?'Kombi-Auftrag · ':''?>Status <?=App\Core\View::e($order['status'])?> · Durchlauf <?= (int)$run['run_no'] ?></p></div><div class="price"><?=number_format((float)$order['current_total'],2,',','.')?> €</div></div>
<section class="card"><h2>Auftragswert im Detail</h2><div class="worklist"><div class="work-row"><div><b>Grundvergütung</b></div><strong><?=number_format((float)$order['base_compensation'],2,',','.')?> €</strong></div>
<?php foreach($orderOptions as $op):?><div class="work-row"><div><b>Option: <?=App\Core\View::e($op['name'])?></b></div><strong><?=number_format((float)$op['price'],2,',','.')?> €</strong></div><?php endforeach;?>
<?php foreach($adjustments as $a): if(in_array($a['adjustment_type'],['option_add','option_remove'],true))continue;?><div class="work-row"><div><b><?=App\Core\View::e($a['label'])?></b><span><?=App\Core\View::e($a['adjustment_type'])?><?php if($a['adjustment_type']==='bonus'&&$a['status']==='reserved'):?> · vorgemerkt<?php endif;?><?php if($a['effective_day_no']):?> · ab Tag <?=$a['effective_day_no']?><?php endif;?></span></div><strong><?=($a['amount']>=0?'+ ':'')?><?=number_format((float)$a['amount'],2,',','.')?> €</strong></div><?php endforeach;?>
<?php foreach($manualExtraDays as $md): if(!$md['is_paid'])continue;?><div class="work-row"><div><b>Bezahlter Zusatztag</b><span><?=App\Core\View::e($md['reason'])?></span></div><strong>+ <?=number_format((float)$md['amount'],2,',','.')?> €</strong></div><?php endforeach;?>
<div class="work-row"><div><b>Aktueller Gesamtbetrag</b></div><strong><?=number_format((float)$order['current_total'],2,',','.')?> €</strong></div></div></section>
<?php if(!$order['started_at']&&$order['phase']==='preparation'&&$offerOptions): $selectedOptionIds=array_map(fn($x)=>(int)$x['offer_option_id'],$orderOptions);?><section class="card admin-form"><h2>Optionsauswahl bis zum Start ändern</h2><p class="muted">Bis zum Auftragsstart kannst du Optionen selbst hinzufügen oder abwählen. Danach sind Änderungen nur noch durch den Betreiber möglich.</p><form method="post" action="/konto/auftraege/<?=$order['id']?>/optionen" class="form-grid"><?=App\Core\Csrf::field()?><div class="full option-list"><?php foreach($offerOptions as $op):?><label><span><input type="checkbox" name="options[]" value="<?=$op['id']?>" <?=in_array((int)$op['id'],$selectedOptionIds,true)?'checked':''?>> <strong><?=App\Core\View::e($op['name'])?></strong></span><span><?=App\Core\View::e($op['description']??'')?></span><b><?=((float)$op['price']>0?'+ '.number_format((float)$op['price'],2,',','.').' €':'kostenlos')?></b></label><?php endforeach;?></div><button class="btn primary full">Optionsauswahl aktualisieren</button></form></section><?php endif;?>
<?php if($components):?><section><h2>Auftragsbestandteile</h2><div class="worklist"><?php foreach($components as $co):?><div class="work-row"><div><b><?=App\Core\View::e($co['title'])?></b><span><?=App\Core\View::e($co['category_name'])?> · <?=App\Core\View::e($co['component_type'])?> · <?=App\Core\View::e($co['status'])?><?php if($co['duration_value']):?> · <?= (int)$co['duration_value'] ?> <?=App\Core\View::e($co['duration_unit']??'')?><?php endif;?></span></div><strong><?=number_format((float)$co['compensation'],2,',','.')?> €</strong></div><?php endforeach;?></div></section><?php endif;?>
<?php if(!$order['started_at'] && $physicalComponents):?><section><h2>1. Artikel je physischem Bestandteil festlegen</h2><?php foreach($physicalComponents as $co): $it=$items[(int)$co['id']]??[];?><div class="card admin-form"><h3><?=App\Core\View::e($co['title'])?></h3><form method="post" action="/konto/auftraege/<?=$order['id']?>/artikel" class="form-grid"><?=App\Core\Csrf::field()?><input type="hidden" name="order_component_id" value="<?=$co['id']?>"><label class="full">Kurze Artikelbezeichnung<input name="short_name" value="<?=App\Core\View::e($it['short_name']??'')?>" required></label><label>Größe (freiwillig)<input name="size" value="<?=App\Core\View::e($it['size']??'')?>"></label><label>Farbe (freiwillig)<input name="color" value="<?=App\Core\View::e($it['color']??'')?>"></label><label>Marke (freiwillig)<input name="brand" value="<?=App\Core\View::e($it['brand']??'')?>"></label><label>Material (freiwillig)<input name="material" value="<?=App\Core\View::e($it['material']??'')?>"></label><button class="btn primary full">Artikel für diesen Bestandteil speichern</button></form></div><?php endforeach;?></section>
<section><h2>2. Vorabkontrolle</h2><p class="muted">Jede geforderte Perspektive wird separat geprüft. Akzeptierte Aufnahmen bleiben akzeptiert; beanstandete Perspektiven können gezielt neu aufgenommen werden.</p><div class="worklist"><?php foreach($precheckRequirements as $pr): $done=(int)$pr['accepted_count']>=(int)$pr['required_count'];?><div class="card admin-form"><div class="section-head compact"><div><b><?=App\Core\View::e($pr['component_title'])?> · <?=App\Core\View::e($pr['label'])?></b><?php if($pr['description']):?><span><?=App\Core\View::e($pr['description'])?></span><?php endif;?></div><strong><?=$pr['accepted_count']?>/<?=$pr['required_count']?> akzeptiert</strong></div><?php if(!$done):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/nachweis" enctype="multipart/form-data" class="form-grid"><?=App\Core\Csrf::field()?><input type="hidden" name="evidence_type" value="precheck"><input type="hidden" name="precheck_requirement_id" value="<?=$pr['id']?>"><label class="full">Foto direkt aufnehmen<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" capture="environment" required></label><button class="btn primary full">Perspektive einreichen</button></form><?php else:?><p class="muted">Diese Pflichtperspektive ist vollständig freigegeben.</p><?php endif;?></div><?php endforeach;?></div></section><?php endif;?>
<?php if($order['started_at']):?><section><h2>Tagesplan</h2><div class="day-grid"><?php foreach($days as $d):?><div class="card day-card"><div><span><?=date('d.m.Y',strtotime($d['calendar_date']))?></span><strong><?= $d['day_type']==='start'?'Starttag':'Tag '.(int)$d['day_no'] ?> · <?=App\Core\View::e($d['component_title']??'')?></strong></div><small><?=App\Core\View::e($d['day_type'])?></small></div><?php endforeach;?></div></section><section><h2>Nachweisfenster</h2><div class="worklist"><?php foreach($windows as $w):?><div class="work-row"><div><b><?=App\Core\View::e($w['component_title']??'')?> · Tag <?=$w['day_no']?> · <?=App\Core\View::e($w['name'])?></b><span><?=date('d.m.Y H:i',strtotime($w['starts_at']))?>–<?=date('H:i',strtotime($w['ends_at']))?> · Nachfrist bis <?=date('H:i',strtotime($w['grace_ends_at']))?> · <?=$w['uploaded_count']?>/<?=$w['required_count']?> eingereicht</span></div><?php if(time()>=strtotime($w['starts_at'])&&time()<=strtotime($w['grace_ends_at'])):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/nachweis" enctype="multipart/form-data" class="inline-upload"><?=App\Core\Csrf::field()?><input type="hidden" name="evidence_type" value="regular"><input type="hidden" name="evidence_window_id" value="<?=$w['id']?>"><input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" capture="environment" required><button class="btn primary">Aufnehmen</button></form><?php endif;?></div><?php endforeach;?></div></section><?php endif;?>
<section><h2>Nachweise</h2><div class="media-grid"><?php foreach($evidences as $e):?><div class="card media-card"><img src="/media/evidence/<?=$e['id']?>" alt="Nachweis"><div><b><?=App\Core\View::e($e['component_title']??'')?><?=!empty($e['component_title'])?' · ':''?><?=App\Core\View::e($e['precheck_label']?:($e['window_name']?:'Nachweis'))?></b><span><?=date('d.m.Y H:i',strtotime($e['created_at']))?> · <?=App\Core\View::e($e['review_status'])?></span><?php if($e['rejection_reason']):?><small><?=App\Core\View::e($e['rejection_reason'])?> <?=App\Core\View::e($e['rejection_note'])?><?php if($e['retake_deadline']):?> · Nachforderung bis <?=date('d.m.Y H:i',strtotime($e['retake_deadline']))?>, Nachfrist bis <?=date('d.m.Y H:i',strtotime($e['retake_grace_ends_at']))?><?php endif;?></small><?php endif;?></div></div><?php endforeach;?></div></section>

<section><h2>Spontane Fotoanforderungen</h2><div class="worklist"><?php foreach($spontaneous as $sr):?><div class="work-row"><div><b><?=App\Core\View::e($sr['motif'])?></b><span><?=App\Core\View::e($sr['description'])?> · <?=$sr['uploaded_count']?>/<?=$sr['requested_count']?> · Frist <?=date('d.m.Y H:i',strtotime($sr['deadline']))?> · Nachfrist bis <?=date('H:i',strtotime($sr['grace_ends_at']))?></span></div><?php if((int)$sr['uploaded_count']<(int)$sr['requested_count'] && time()<=strtotime($sr['grace_ends_at'])):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/spontan" enctype="multipart/form-data" class="inline-upload"><?=App\Core\Csrf::field()?><input type="hidden" name="request_id" value="<?=$sr['id']?>"><input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" capture="environment" required><button class="btn primary">Foto einreichen</button></form><?php else:?><strong><?=App\Core\View::e($sr['status'])?></strong><?php endif;?></div><?php endforeach;?><?php if(!$spontaneous):?><div class="empty">Keine spontanen Fotoanforderungen.</div><?php endif;?></div></section>
<section><h2>Zusatzaufgaben</h2><div class="worklist"><?php foreach($tasks as $tx):?><?php $cfg=json_decode($tx['config_json']?:'{}',true)?:[];$fields=$cfg['fields']??[];?><div class="task-card card"><div class="task-head"><div><b><?=App\Core\View::e($tx['title'])?></b><span><?=App\Core\View::e($tx['description'])?></span></div><small>Fällig <?=date('d.m.Y H:i',strtotime($tx['due_at']))?> · Nachfrist bis <?=date('H:i',strtotime($tx['grace_ends_at']))?> · <?=App\Core\View::e($tx['review_status'])?></small></div><?php if(!$tx['submitted_at'] && time()<=strtotime($tx['grace_ends_at'])):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/aufgaben/<?=$tx['id']?>" class="form-grid"><?=App\Core\Csrf::field()?><?php foreach($fields as $field):?><?php $key=(string)($field['key']??'feld');$type=(string)($field['type']??'text');$label=(string)($field['label']??$key);$required=!empty($field['required']);?><label class="<?=$type==='multiselect'?'full':''?>"><?=App\Core\View::e($label)?><?php if($type==='number'):?><input type="number" name="field[<?=App\Core\View::e($key)?>]" <?=$required?'required':''?>><?php elseif($type==='scale'):?><input type="range" name="field[<?=App\Core\View::e($key)?>]" min="<?= (int)($field['min']??1) ?>" max="<?= (int)($field['max']??10) ?>" value="<?= (int)($field['min']??1) ?>"><?php elseif($type==='boolean'):?><select name="field[<?=App\Core\View::e($key)?>]" <?=$required?'required':''?>><option value="">Bitte wählen</option><option value="1">Ja</option><option value="0">Nein</option></select><?php elseif($type==='select'):?><select name="field[<?=App\Core\View::e($key)?>]" <?=$required?'required':''?>><option value="">Bitte wählen</option><?php foreach(($field['options']??[]) as $opt):?><option value="<?=App\Core\View::e($opt)?>"><?=App\Core\View::e($opt)?></option><?php endforeach;?></select><?php elseif($type==='multiselect'||$type==='checkboxes'):?><div class="checkbox-grid"><?php foreach(($field['options']??[]) as $opt):?><label class="check"><input type="checkbox" name="field[<?=App\Core\View::e($key)?>][]" value="<?=App\Core\View::e($opt)?>"><span><?=App\Core\View::e($opt)?></span></label><?php endforeach;?></div><?php else:?><input type="text" name="field[<?=App\Core\View::e($key)?>]" <?=$required?'required':''?>><?php endif;?></label><?php endforeach;?><button class="btn primary full">Aufgabe einreichen</button></form><?php endif;?></div><?php endforeach;?><?php if(!$tasks):?><div class="empty">Keine Zusatzaufgaben.</div><?php endif;?></div></section>
<section><h2>Beschädigung / Unbrauchbarkeit</h2><?php if($order['started_at']&&$physicalComponents):?><div class="card admin-form"><form method="post" action="/konto/auftraege/<?=$order['id']?>/beschaedigung" enctype="multipart/form-data" class="form-grid"><?=App\Core\Csrf::field()?><label class="full">Betroffener Bestandteil<select name="order_component_id" required><?php foreach($physicalComponents as $co):?><option value="<?=$co['id']?>"><?=App\Core\View::e($co['title'].' · '.$co['category_name'])?></option><?php endforeach;?></select></label><label class="full">Grund<textarea name="reason" rows="3" required></textarea></label><label class="full">Pflichtfoto<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" capture="environment" required></label><button class="btn full">Beschädigung melden</button></form></div><?php endif;?><div class="worklist"><?php foreach($damageCases as $dc):?><div class="work-row"><div><b>Beschädigung #<?=$dc['id']?><?=!empty($dc['component_title'])?' · '.App\Core\View::e($dc['component_title']):''?></b><span><?=App\Core\View::e($dc['reason'])?> · <?=App\Core\View::e($dc['status'])?> · <?=date('d.m.Y H:i',strtotime($dc['created_at']))?></span></div></div><?php endforeach;?></div><?php foreach($damageRequests as $dr):?><?php if($dr['status']==='requested'):?><div class="card admin-form"><h3>Nachforderung #<?=$dr['id']?></h3><p><?=App\Core\View::e($dr['instructions'])?></p><p class="muted">Frist <?=date('d.m.Y H:i',strtotime($dr['deadline']))?> · Nachfrist <?=date('d.m.Y H:i',strtotime($dr['grace_ends_at']))?></p><form method="post" action="/konto/auftraege/<?=$order['id']?>/beschaedigung/nachforderung/<?=$dr['id']?>" enctype="multipart/form-data" class="form-grid"><?=App\Core\Csrf::field()?><?php if(in_array($dr['field_type'],['photo','video'],true)):?><label class="full">Datei<input type="file" name="evidence" accept="<?=$dr['field_type']==='video'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp'?>" <?=$dr['field_type']==='photo'?'capture="environment"':''?> required></label><?php else:?><label class="full">Antwort<textarea name="response" rows="3" required></textarea></label><?php endif;?><button class="btn primary full">Nachforderung einreichen</button></form></div><?php endif;?><?php endforeach;?></section>
<?php if($digitalComponents):?><section><h2>Digitale Abgabe & Versionen</h2>
<?php foreach($digitalComponents as $dc): $req=json_decode($dc['requirements_json']?:'{}',true)?:[];$versions=$digitalVersions[$dc['id']]??[];?>
<div class="card admin-form"><div class="section-head compact"><div><h3><?=App\Core\View::e($req['title']??$dc['component_title'])?></h3><p class="muted">Format <?=App\Core\View::e($dc['format_type'])?> · Status <?=App\Core\View::e($dc['status'])?></p></div><strong><?=number_format((float)$dc['compensation'],2,',','.')?> €</strong></div>
<?php if($req):?><details><summary>Anforderungen anzeigen</summary><pre class="json-preview"><?=App\Core\View::e(json_encode($req,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre></details><?php endif;?>
<?php if(!in_array($dc['status'],['accepted','partially_accepted','rejected'],true)):?>
<form method="post" action="/konto/auftraege/<?=$order['id']?>/digital/<?=$dc['id']?>/upload" enctype="multipart/form-data" class="form-grid"><?=App\Core\Csrf::field()?>
<label>Inhaltstyp<select name="content_type"><option value="text">Text</option><option value="audio">Audio</option><option value="video">Video</option></select></label>
<label class="full">Textinhalt<textarea name="text_content" rows="7" placeholder="Nur bei Text-Abgabe ausfüllen"></textarea></label>
<label class="full">Audio-/Videodatei<input type="file" name="digital_file" accept="audio/*,video/mp4,video/webm,video/quicktime"></label>
<button class="btn full">Neue Version speichern</button></form>
<?php if($versions):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/digital/<?=$dc['id']?>/einreichen"><?=App\Core\Csrf::field()?><button class="btn primary">Aktuelle Version final einreichen</button></form><?php endif;?>
<?php endif;?>
<div class="worklist"><?php foreach($versions as $v):?><div class="card"><div class="section-head compact"><b>V<?=$v['version_no']?> · <?=App\Core\View::e($v['content_type'])?></b><span><?=date('d.m.Y H:i',strtotime($v['created_at']))?></span></div>
<?php if($v['content_type']==='text'):?><div class="digital-text"><?=nl2br(App\Core\View::e($v['text_content']))?></div>
<?php elseif(str_starts_with((string)$v['mime_type'],'audio/')):?><audio controls controlsList="nodownload noplaybackrate" preload="metadata" src="/media/digital/<?=$v['id']?>"></audio>
<?php else:?><video controls controlsList="nodownload noplaybackrate" disablePictureInPicture preload="metadata" src="/media/digital/<?=$v['id']?>"></video><?php endif;?>
</div><?php endforeach;?><?php if(!$versions):?><div class="empty">Noch keine Version gespeichert.</div><?php endif;?></div>
<?php foreach(($revisionRounds[$dc['id']]??[]) as $rr):?><div class="card"><h4>Revision <?=$rr['round_no']?> · <?=App\Core\View::e($rr['status'])?></h4><p class="muted">Frist <?=date('d.m.Y H:i',strtotime($rr['deadline']))?> · Nachfrist bis <?=date('d.m.Y H:i',strtotime($rr['grace_ends_at']))?></p><div class="worklist"><?php foreach(($revisionItems[$rr['id']]??[]) as $ri):?><div class="work-row"><div><b><?=App\Core\View::e($ri['description'])?></b></div><strong><?=App\Core\View::e($ri['status'])?></strong></div><?php endforeach;?></div></div><?php endforeach;?>
</div><?php endforeach;?></section><?php endif;?>
<?php if($shipping):?><section><h2>Versand & Empfängeradresse</h2>
<div class="card"><p><b><?=App\Core\View::e($shipping['recipient_name']??'')?></b><br><?=App\Core\View::e($shipping['street']??'')?><br><?=App\Core\View::e(($shipping['postal_code']??'').' '.($shipping['city']??''))?> · <?=App\Core\View::e($shipping['country_code']??'DE')?></p><p class="muted">Versandstatus: <?=App\Core\View::e($shipping['shipment_status']??$shipping['status'])?><?php if($shipping['tracking_number']):?> · Tracking: <?=App\Core\View::e($shipping['tracking_number'])?><?php endif;?></p></div>
<div class="worklist"><?php $previousComplete=true; foreach($shippingSteps as $st): $cfg=json_decode($st['config_json']?:'{}',true)?:[];$type=$cfg['type']??'checkbox';?><div class="card"><div class="task-head"><div><b><?=$st['step_no']?>. <?=App\Core\View::e($st['title'])?></b><span><?=App\Core\View::e($st['instructions']??'')?></span></div><strong><?=App\Core\View::e($st['status'])?></strong></div>
<?php if($st['status']!=='completed' && $previousComplete):?><form method="post" action="/konto/auftraege/<?=$order['id']?>/versand/<?=$st['id']?>" enctype="multipart/form-data" class="form-grid"><?=App\Core\Csrf::field()?>
<?php if($type==='photo'):?><label class="full">Foto<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp" capture="environment" required></label>
<?php elseif($type==='tracking_or_receipt'):?><label>Trackingnummer<input name="tracking_number"></label><label>Einlieferungsbeleg<input type="file" name="evidence" accept="image/jpeg,image/png,image/webp,application/pdf"></label>
<?php else:?><label class="check full"><input type="checkbox" name="confirmed" value="1" required> Schritt bestätigen</label><?php endif;?>
<?php if(!empty($cfg['text'])):?><label class="full">Angabe<textarea name="text" rows="2"></textarea></label><?php endif;?>
<button class="btn primary full">Schritt abschließen</button></form><?php endif;?>
</div><?php if($st['status']!=='completed')$previousComplete=false; endforeach;?></div></section><?php endif;?>
<?php if($finalReview):?><section class="card"><h2>Abschlussentscheidung</h2><p><b><?=App\Core\View::e($finalReview['decision'])?></b> · freigegeben <?=number_format((float)$finalReview['approved_amount'],2,',','.')?> €</p><?php if($finalReview['seller_message']):?><p><?=App\Core\View::e($finalReview['seller_message'])?></p><?php endif;?></section><?php endif;?>
<?php if($violations):?><section><h2>Verstöße / Prüfungen</h2><div class="worklist"><?php foreach($violations as $v):?><div class="work-row"><div><b><?=App\Core\View::e($v['violation_type'])?></b><span><?=App\Core\View::e($v['description'])?></span></div><strong><?=App\Core\View::e($v['status'])?></strong></div><?php endforeach;?></div></section><?php endif;?>
<section class="card chat"><h2>Auftragschat</h2><div class="chat-log"><?php foreach($messages as $m):?><div class="message <?=$m['sender_type']?>"><small><?=App\Core\View::e($m['sender_type'])?> · <?=date('d.m. H:i',strtotime($m['created_at']))?></small><p><?=nl2br(App\Core\View::e($m['message']))?></p></div><?php endforeach;?></div><form method="post" action="/konto/auftraege/<?=$order['id']?>/chat" class="chat-form"><?=App\Core\Csrf::field()?><textarea name="message" rows="3" required placeholder="Nachricht schreiben"></textarea><button class="btn primary">Senden</button></form></section></main>