INSERT IGNORE INTO categories(parent_id,name,slug,icon,is_system_template,is_digital,is_active,sort_order,created_at,updated_at) VALUES
(NULL,'Getragene Socken','getragene-socken','socks',1,0,1,10,NOW(),NOW()),
(NULL,'Schuhe','schuhe','shoe',1,0,1,20,NOW(),NOW()),
(NULL,'Slips','slips','briefs',1,0,1,30,NOW(),NOW()),
(NULL,'Tops','tops','shirt',1,0,1,40,NOW(),NOW()),
(NULL,'BHs','bhs','bra',1,0,1,50,NOW(),NOW()),
(NULL,'Strumpfhosen','strumpfhosen','tights',1,0,1,60,NOW(),NOW()),
(NULL,'Nylons','nylons','tights',1,0,1,70,NOW(),NOW()),
(NULL,'Feinstrümpfe','feinstruempfe','socks',1,0,1,80,NOW(),NOW()),
(NULL,'Kniestrümpfe','kniestruempfe','socks',1,0,1,90,NOW(),NOW()),
(NULL,'Overknees','overknees','socks',1,0,1,100,NOW(),NOW()),
(NULL,'Leggings','leggings','pants',1,0,1,110,NOW(),NOW()),
(NULL,'Shorts','shorts','pants',1,0,1,120,NOW(),NOW()),
(NULL,'Hotpants','hotpants','pants',1,0,1,130,NOW(),NOW()),
(NULL,'Sportkleidung','sportkleidung','sport',1,0,1,140,NOW(),NOW()),
(NULL,'T-Shirts','t-shirts','shirt',1,0,1,150,NOW(),NOW()),
(NULL,'Pullover','pullover','shirt',1,0,1,160,NOW(),NOW()),
(NULL,'Hoodies','hoodies','shirt',1,0,1,170,NOW(),NOW()),
(NULL,'Schlafkleidung','schlafkleidung','moon',1,0,1,180,NOW(),NOW()),
(NULL,'Pyjamas','pyjamas','moon',1,0,1,190,NOW(),NOW()),
(NULL,'Bodys','bodys','body',1,0,1,200,NOW(),NOW()),
(NULL,'Bikinis','bikinis','swim',1,0,1,210,NOW(),NOW()),
(NULL,'Badeanzüge','badeanzuege','swim',1,0,1,220,NOW(),NOW()),
(NULL,'Handschuhe','handschuhe','gloves',1,0,1,230,NOW(),NOW()),
(NULL,'Mützen','muetzen','hat',1,0,1,240,NOW(),NOW()),
(NULL,'Caps','caps','hat',1,0,1,250,NOW(),NOW()),
(NULL,'Schals','schals','scarf',1,0,1,260,NOW(),NOW()),
(NULL,'Einlegesohlen','einlegesohlen','sole',1,0,1,270,NOW(),NOW()),
(NULL,'Schnürsenkel','schnuersenkel','laces',1,0,1,280,NOW(),NOW()),
(NULL,'Arbeitskleidung','arbeitskleidung','work',1,0,1,290,NOW(),NOW()),
(NULL,'Berufskleidung','berufskleidung','work',1,0,1,300,NOW(),NOW()),
(NULL,'Kostüm-/Cosplay-Kleidung','kostuem-cosplay','costume',1,0,1,310,NOW(),NOW()),
(NULL,'Dessous','dessous','lingerie',1,0,1,320,NOW(),NOW()),
(NULL,'Persönliche Accessoires','persoenliche-accessoires','accessory',1,0,1,330,NOW(),NOW()),
(NULL,'Haare/Haarsträhnen','haare-haarstraehnen','hair',1,0,1,340,NOW(),NOW()),
(NULL,'Spucke','spucke','drop',1,0,1,350,NOW(),NOW()),
(NULL,'Individuelle Sets','individuelle-sets','set',1,0,1,360,NOW(),NOW()),
(NULL,'Sonstiges','sonstiges','other',1,0,1,370,NOW(),NOW()),
(NULL,'Digitale Inhalte','digitale-inhalte','digital',1,1,1,380,NOW(),NOW()),
(NULL,'Wichsanleitung','wichsanleitung','digital',1,1,1,390,NOW(),NOW());

INSERT IGNORE INTO settings(setting_key,setting_value,updated_at) VALUES
('platform_name','FetischShop',NOW()),
('timezone','Europe/Berlin',NOW()),
('currency','EUR',NOW()),
('minimum_payout','25.00',NOW()),
('payout_bank_enabled','1',NOW()),
('payout_paypal_enabled','1',NOW()),
('evidence_grace_minutes','60',NOW()),
('spontaneous_grace_minutes','60',NOW()),
('task_grace_minutes','60',NOW()),
('terms_version','2026-09-20',NOW()),
('privacy_version','2026-09-20',NOW()),
('content_rules_version','2026-09-20',NOW()),
('evidence_rules_version','2026-09-20',NOW()),
('shipping_rules_version','2026-09-20',NOW()),
('wallet_rules_version','2026-09-20',NOW()),
('digital_rights_version','2026-09-20',NOW());
