<main class="section narrow"><span class="eyebrow">Hilfe</span><h1>Häufige Fragen</h1><div class="faq">
<details open><summary>Wer kann sich registrieren?</summary><p>Die Plattform ist ausschließlich für volljährige Verkäuferinnen bestimmt. Bei der Registrierung werden Geburtsdatum und die Bestätigung der Volljährigkeit verlangt. Neue Aufträge können erst nach bestätigter E-Mail-Adresse angenommen werden.</p></details>
<details><summary>Wer kauft meine Artikel oder Inhalte?</summary><p>Ausschließlich der Betreiber der Plattform. Es gibt keine Käuferkonten, keine öffentlichen Verkäuferprofile und keinen Handel zwischen Verkäuferinnen und anderen Plattformnutzern.</p></details>
<details><summary>Kann ich Ware oder Inhalte einer anderen Person anbieten?</summary><p>Nein. Aufträge, Artikel, Fotos, Videos, Audios und sonstige Inhalte müssen von der registrierten Verkäuferin selbst stammen beziehungsweise selbst erstellt und erfüllt werden.</p></details>
<details><summary>Warum kann ich ein Angebot manchmal nicht annehmen?</summary><p>Ein Angebot kann zum Beispiel blockiert sein, wenn deine E-Mail-Adresse noch nicht bestätigt ist, die Annahmefrist abgelaufen ist oder eine Kategorie des Angebots bereits durch einen aktiven Auftrag belegt ist.</p></details>
<details><summary>Was passiert nach der Annahme?</summary><p>Die zu diesem Zeitpunkt gültige Angebotsversion wird als Auftrag gespeichert. Vergütung, Optionen, Regeln und Bestandteile werden festgehalten. Bei physischen Aufträgen folgt in der Regel zunächst die Artikelwahl und Vorabkontrolle.</p></details>
<details><summary>Wo sehe ich meine nächsten Fristen?</summary><p>Im Verkäuferinnen-Bereich gibt es „Fristen & Kalender“. Dort werden offene Nachweise, Zusatzaufgaben, spontane Fotoanforderungen, Revisionen, Beschädigungsnachforderungen und Versandfristen zeitlich sortiert angezeigt.</p></details>
<details><summary>Was passiert, wenn ich einen Nachweis verpasse?</summary><p>Nach Ablauf der eigentlichen Frist kann – sofern für den Vorgang vorgesehen – noch eine Nachfrist bestehen. Ein technisches Versäumnis wird zunächst als Prüffall behandelt. Erst eine administrative Bestätigung macht daraus einen bestätigten Verstoß.</p></details>
<details><summary>Was mache ich bei einem beschädigten oder unbrauchbaren Artikel?</summary><p>Nutze den Beschädigungsvorgang im Auftrag. Du reichst den Grund und den geforderten Nachweis ein. Ein Artikelwechsel oder Neustart erfolgt nur über diesen geregelten Ablauf.</p></details>
<details><summary>Wann bekomme ich die Versandadresse?</summary><p>Die konkrete Empfängeradresse wird erst freigegeben, wenn der physische Auftrag die Versandphase erreicht hat. Anschließend arbeitest du die angezeigten Versandschritte der Reihe nach ab.</p></details>
<details><summary>Wie funktionieren digitale Abgaben?</summary><p>Digitale Inhalte werden direkt im geschützten Auftrag hochgeladen und versioniert. Frühere Versionen bleiben erhalten. Wenn Änderungen erforderlich sind, erhältst du konkrete Revisionspunkte mit eigener Frist.</p></details>
<details><summary>Was bedeutet der Rechte-Status bei digitalen Inhalten?</summary><p>Die für Upload und Prüfung erforderliche Zustimmung wird bei der Auftragsannahme dokumentiert. Nach der Prüfung zeigt der Auftrag, ob weitergehende Rechte entsprechend der vereinbarten Regelung freigegeben oder nicht freigegeben wurden.</p></details>
<details><summary>Wann wird ausgezahlt?</summary><p>Erst nach dem vorgesehenen Versand beziehungsweise der digitalen Abgabe und Abschlussprüfung. Das Wallet unterscheidet „Vorgemerkt“, „In Prüfung“ und „Verfügbar“. Nur verfügbares Guthaben kann zur Auszahlung beantragt werden.</p></details>
<details><summary>Kann ich sehen, welchem Auftrag eine Auszahlung zugeordnet wurde?</summary><p>Ja. Im Wallet zeigt der Auszahlungsverlauf, welche freigegebenen Aufträge ganz oder teilweise durch eine Auszahlung abgegolten wurden.</p></details>
<details><summary>Was passiert nach vollständiger Auszahlung?</summary><p>Wenn der vollständig freigegebene Betrag eines Auftrags ausgezahlt wurde, wird der Auftrag archiviert. Die Historie bleibt sichtbar; der Auftragschat kann dann schreibgeschützt sein.</p></details>
<details><summary>Was passiert bei einem technischen Plattformausfall?</summary><p>Dokumentiert der Betreiber einen tatsächlichen Plattformausfall, werden betroffene Fristen nach den Systemregeln angepasst. Eigene Verbindungs- oder Geräteprobleme gelten nicht automatisch als Plattformausfall.</p></details>
</div><div class="actions"><a class="btn primary" href="/regeln">Plattformregeln</a><a class="btn ghost" href="/kontakt">Kontakt</a></div></main>