<main class="section narrow"><span class="eyebrow">Ablauf</span><h1>So funktioniert die Plattform</h1><p class="muted">Von der Registrierung bis zur Auszahlung läuft jeder Auftrag in nachvollziehbaren Schritten ab.</p><div class="steps">
<div><b>01</b><h3>Registrieren & E-Mail bestätigen</h3><p>Du legst dein persönliches Verkäuferinnen-Konto an, bestätigst die Volljährigkeit und anschließend deine E-Mail-Adresse. Erst danach können neue Aufträge angenommen werden.</p></div>
<div><b>02</b><h3>Angebot prüfen</h3><p>Vor der Annahme siehst du Vergütung, Dauer, Bestandteile, Nachweisfenster, Aufgaben, Optionen und Versand- beziehungsweise digitale Abgabeanforderungen. Das System zeigt dir außerdem, wenn eine Kategorie bereits durch einen laufenden Auftrag belegt ist.</p></div>
<div><b>03</b><h3>Auftrag verbindlich annehmen</h3><p>Mit der Annahme wird die konkrete Angebotsversion fest als Auftrag gespeichert. Die Vergütung wird zunächst im Wallet vorgemerkt. Bei digitalen Bestandteilen wird die erforderliche Rechtevereinbarung dokumentiert.</p></div>
<div><b>04</b><h3>Artikel & Vorabkontrolle</h3><p>Bei physischen Aufträgen legst du zuerst den konkreten Artikel fest und reichst die geforderten Perspektiven ein. Der Auftrag startet erst, wenn die Vorabkontrolle vollständig freigegeben wurde.</p></div>
<div><b>05</b><h3>Durchführung</h3><p>Im Auftrag und unter „Fristen & Kalender“ siehst du laufende Nachweisfenster, Zusatzaufgaben, spontane Fotoanforderungen und eventuelle Nachforderungen. Wichtige Ereignisse können zusätzlich als In-App-Benachrichtigung und E-Mail versendet werden.</p></div>
<div><b>06</b><h3>Beschädigung oder Nachforderung</h3><p>Wenn ein Artikel beschädigt oder unbrauchbar wird, meldest du das direkt im Auftrag. Der Betreiber kann weitere Nachweise anfordern oder einen Neustart mit neuem Artikel freigeben.</p></div>
<div><b>07</b><h3>Versand oder digitale Abgabe</h3><p>Physische Bestandteile durchlaufen einen Schritt-für-Schritt-Versandworkflow. Digitale Inhalte werden geschützt hochgeladen, versioniert und bei Bedarf in konkreten Revisionsrunden nachbearbeitet.</p></div>
<div><b>08</b><h3>Abschlussprüfung</h3><p>Nach Eingang beziehungsweise digitaler Prüfung entscheidet der Betreiber über den Auftrag. Im Auftrag siehst du die Entscheidung, den freigegebenen Betrag und eine eventuelle Mitteilung.</p></div>
<div><b>09</b><h3>Wallet & Auszahlung</h3><p>Der Betrag wechselt von „Vorgemerkt“ über „In Prüfung“ zu „Verfügbar“. Verfügbares Guthaben kannst du über eine hinterlegte Auszahlungsmethode beantragen.</p></div>
<div><b>10</b><h3>Archiv</h3><p>Nach vollständiger Auszahlung wird der Auftrag archiviert. Die Historie bleibt im Verkäuferinnen-Bereich nachvollziehbar; der Auftragschat kann anschließend nur noch lesbar sein.</p></div>
</div><div class="actions"><a class="btn primary" href="/registrieren">Konto erstellen</a><a class="btn ghost" href="/regeln">Plattformregeln lesen</a></div></main>