<main class="section narrow legal">
<span class="eyebrow">Klare Vorgaben</span><h1>Plattformregeln</h1>
<div class="notice">Diese Regeln beschreiben die praktische Nutzung der Plattform. Ergänzend gelten die Plattform- und Verkäuferbedingungen.</div>

<section><h2>1. Nur volljährige Verkäuferinnen</h2><p>Ein Verkäuferinnen-Konto darf nur von einer volljährigen Person selbst genutzt werden. Konten dürfen nicht geteilt, verliehen oder stellvertretend für andere Personen verwendet werden.</p></section>
<section><h2>2. Nur eigene Artikel und eigene Inhalte</h2><p>Artikel, Fotos, Videos, Audios, Texte und sonstige Nachweise müssen von der registrierten Verkäuferin selbst stammen beziehungsweise von ihr selbst für den Auftrag erstellt worden sein. Fremdware, fremde Inhalte und stellvertretend erfüllte Aufträge sind nicht erlaubt.</p></section>
<section><h2>3. Keine Minderjährigen und keine nicht einwilligenden Dritten</h2><p>Minderjährige dürfen weder sichtbar noch hörbar noch anderweitig Bestandteil eines Auftrags oder Nachweises sein. Gleiches gilt für andere Personen ohne erforderliche Einwilligung.</p></section>
<section><h2>4. Angebot vor Annahme vollständig prüfen</h2><p>Vor einer verbindlichen Annahme sind Vergütung, Dauer, Bestandteile, Nachweise, Zusatzaufgaben, Optionen, mögliche Verlängerungen sowie Versand- oder digitale Abgabeanforderungen zu prüfen. Nach der Annahme wird die zu diesem Zeitpunkt gültige Angebotsversion fest mit dem Auftrag verbunden.</p></section>
<section><h2>5. Fristen und Nachweisfenster beachten</h2><p>Pflichtnachweise, Zusatzaufgaben, spontane Fotoanforderungen, Revisionen und Nachforderungen müssen innerhalb der im Auftrag angezeigten Frist eingereicht werden. Wenn eine Nachfrist besteht, wird sie separat angezeigt. Der Bereich „Fristen & Kalender“ dient als zusätzliche Übersicht; maßgeblich bleibt der konkrete Auftrag.</p></section>
<section><h2>6. Nachweise unverändert einreichen</h2><p>Geforderte Nachweise sind aktuell, auftragsbezogen und entsprechend der konkreten Anweisung einzureichen. Beanstandete Aufnahmen werden nicht ersetzt oder überschrieben, sondern bleiben als Teil der Auftragshistorie erhalten; Nachaufnahmen werden zusätzlich gespeichert.</p></section>
<section><h2>7. Artikelwechsel nur über den vorgesehenen Ablauf</h2><p>Ein normaler Artikelwechsel nach Beginn der physischen Durchführung ist nicht vorgesehen. Bei Beschädigung oder Unbrauchbarkeit muss der Beschädigungsvorgang verwendet werden. Ein Neustart erfolgt nur nach Anerkennung durch den Betreiber.</p></section>
<section><h2>8. Zusatzaufgaben und spontane Anforderungen</h2><p>Während eines laufenden Auftrags können zusätzliche, zum Auftrag gehörende Aufgaben oder Fotoanforderungen gestellt werden. Sie werden mit Frist und – sofern vorgesehen – Nachfrist angezeigt und einem konkreten Auftragsbestandteil zugeordnet.</p></section>
<section><h2>9. Verstöße werden geprüft</h2><p>Ein automatischer Frist- oder Nachweisfehler ist zunächst ein Prüffall. Erst die administrative Bestätigung macht daraus einen bestätigten Verstoß. Mögliche zusätzliche Durchführungstage werden dem betroffenen Bestandteil zugeordnet.</p></section>
<section><h2>10. Versand erst nach Freigabe</h2><p>Physische Artikel werden erst versendet, wenn der Versandbereich im Auftrag freigeschaltet wurde. Die dort angezeigten Schritte sind der Reihe nach abzuarbeiten. Die Empfängeradresse darf ausschließlich für die Abwicklung des konkreten Auftrags verwendet werden.</p></section>
<section><h2>11. Digitale Inhalte ausschließlich über die Plattform</h2><p>Digitale Abgaben werden über den geschützten Uploadbereich eingereicht und versioniert. Bei einer Revision müssen die angezeigten Änderungspunkte innerhalb der gesetzten Frist bearbeitet werden. Der jeweilige Rechte-Status wird im Auftrag angezeigt.</p></section>
<section><h2>12. Kommunikation nur auftragsbezogen</h2><p>Der Auftragschat dient ausschließlich der Abwicklung des jeweiligen Auftrags. Nach vollständigem Abschluss und Archivierung kann der Chat schreibgeschützt werden.</p></section>
<section><h2>13. Wallet ist kein Bankkonto</h2><p>Vorgemerkte und in Prüfung befindliche Beträge sind noch nicht auszahlbar. Erst als „Verfügbar“ ausgewiesenes Guthaben kann nach den konfigurierten Auszahlungsregeln beantragt werden.</p></section>
<section><h2>14. Technische Ausfälle</h2><p>Bei einem vom Betreiber dokumentierten Plattformausfall werden betroffene Fristen nach den Systemregeln angepasst. Eigene Geräte-, Internet- oder Kameraprobleme gelten nicht automatisch als Plattformausfall.</p></section>
<section><h2>15. Rechtswidrige Inhalte sind ausgeschlossen</h2><p>Nicht zulässig sind insbesondere rechtswidrige Inhalte oder Gegenstände, heimliche Aufnahmen, Inhalte ohne ausreichende Rechte sowie alles, dessen Besitz, Herstellung, Übertragung oder Versand gesetzlich verboten ist.</p></section>

<div class="actions"><a class="btn primary" href="/angebote">Angebote ansehen</a><a class="btn ghost" href="/bedingungen">Vertragsbedingungen</a></div>
</main>