<main class="section narrow legal"><span class="eyebrow">Vertragsunterlagen</span><h1>Plattform- und Verkäuferbedingungen – Entwurf</h1><div class="notice"><strong>Rechtlicher Hinweis:</strong> Die folgenden Bedingungen sind ein umfassender Vertragsentwurf für die technische Umsetzung. Sie müssen vor Verwendung durch eine qualifizierte Rechtsberatung geprüft und an Betreiber, Steuer-/Gewerbesituation und das konkrete Geschäftsmodell angepasst werden.</div>
<section><h2>1. Plattformmodell</h2><p>Die Plattform ist eine Ankaufsplattform. Vertragspartner auf Käuferseite ist ausschließlich der Betreiber. Es gibt keine Käuferregistrierung, keinen öffentlichen Marktplatz zwischen Dritten und keine öffentlichen Verkäuferinnenprofile.</p></section>
<section><h2>2. Volljährigkeit und eigene Leistungen</h2><p>Die Nutzung als Verkäuferin ist ausschließlich volljährigen Personen gestattet. Jeder Auftrag ist persönlich durch die registrierte Verkäuferin zu erfüllen. Verwendete Artikel, Fotos, Videos, Audios und sonstige digitale Inhalte müssen von ihr selbst stammen beziehungsweise von ihr selbst für den Auftrag erstellt worden sein. Inhalte nicht einwilligender Dritter sowie Inhalte Minderjähriger sind ausgeschlossen.</p></section>
<section><h2>3. Angebote und Vertragsschluss</h2><p>Der Betreiber veröffentlicht allgemeine oder individuelle Ankaufangebote. Vor Annahme werden insbesondere Vergütung, Laufzeit oder Erfüllungsmodell, Nachweise, Optionen, Versand- oder Abgabeanforderungen und mögliche Folgen bestätigter Verstöße angezeigt. Mit verbindlicher Annahme wird die zu diesem Zeitpunkt geltende Angebotsversion als Auftragssnapshot gespeichert.</p></section>
<section><h2>4. Start und Vorabkontrolle</h2><p>Bei auftragsbezogener Vorabkontrolle beginnt die Durchführung erst nach vollständiger Freigabe der geforderten Aufnahmen durch den Betreiber. Bereits akzeptierte Aufnahmen bleiben bei Nachforderungen akzeptiert. Eine Vorabkontrolle dient ausschließlich der visuellen Auftrags- und Eignungsdokumentation und stellt keine medizinische Diagnose dar.</p></section>
<section><h2>5. Nachweise und Fristen</h2><p>Pflichtnachweise sind innerhalb der angezeigten Zeitfenster einzureichen. Soweit im Auftrag nichts Abweichendes ausgewiesen ist, beträgt die technische Nachfrist für verpasste reguläre Nachweise, spontane Fotoanforderungen und Zusatzaufgaben höchstens eine Stunde. Originaldateien werden nicht überschrieben; Nachaufnahmen werden als neue Nachweise gespeichert.</p></section>
<section><h2>6. Verstöße und Verlängerungstage</h2><p>Automatisch festgestellte Abweichungen gelten zunächst als mögliche Verstöße und werden administrativ geprüft. Grundsätzlich kann ein bestätigter Verstoß einen zusätzlichen unbezahlten Durchführungstag auslösen. Fehlen mehrere einzeln geforderte Pflichtfotos, können sie jeweils separat geprüft werden. Manuelle Zusatztage können zusätzlich angeordnet werden; bei bezahlten Zusatztagen wird der konkrete Zusatzbetrag angezeigt.</p></section>
<section><h2>7. Beschädigung und Neustart</h2><p>Eine Beschädigung oder Unbrauchbarkeit ist über den vorgesehenen Vorgang mit Nachweis zu melden. Während der Prüfung laufen Auftrag und Fristen grundsätzlich weiter. Nur bei anerkannter Beschädigung kann ein vollständiger Neustart mit neuem Artikel und neuer Vorabkontrolle erfolgen. Frühere Durchläufe, bereits bestätigte Verstöße und die dazugehörige Historie bleiben nachvollziehbar.</p></section>
<section><h2>8. Versand</h2><p>Die konkrete Empfängeradresse wird erst in der Versandphase angezeigt. Der im Auftrag definierte Versandworkflow ist in der vorgesehenen Reihenfolge auszuführen. Versand gilt als nachgewiesen, wenn die verlangte Trackingnummer oder ein zulässiger Einlieferungs-/Annahmebeleg vorliegt. Besondere Verpackungsvorgaben eines Angebots sind einzuhalten.</p></section>
<section><h2>9. Digitale Aufträge</h2><p>Digitale Aufträge können Text-, Audio-, Video- oder kombinierte Bestandteile umfassen. Technische Anforderungen, Fristen und Annahmekriterien ergeben sich aus dem jeweiligen Auftrag. Uploads werden versioniert; frühere Versionen werden nicht überschrieben. Revisionen können mit konkreten Änderungspunkten und Frist angefordert werden.</p></section>
<section><h2>10. Rechte an digitalen Inhalten</h2><p>Beim Upload werden zunächst nur die für Speicherung, technische Verarbeitung, interne Prüfung und Wiedergabe erforderlichen Rechte eingeräumt. Die im jeweiligen Auftrag vereinbarte umfassendere Rechteübertragung soll erst mit erfolgreicher Abnahme und Vergütungsfreigabe wirksam werden. Soweit rechtlich wirksam vereinbart, kann diese insbesondere exklusive, zeitlich und räumlich unbeschränkte Nutzung, Speicherung, Bearbeitung, Vervielfältigung, Veröffentlichung, Weitergabe und Unterlizenzierung umfassen. Bei vollständiger Ablehnung soll die umfassende reguläre Rechteübertragung nicht vollständig eintreten; vereinbarte Archiv-/Nachweisrechte und ein ausdrücklich vereinbartes privates Nutzungsrecht können bestehen bleiben. Bei vergüteter Teilannahme kann vertraglich vorgesehen werden, dass die vereinbarten Rechte am gesamten eingereichten Inhalt einschließlich Versionen, Entwürfen und Revisionen übergehen. Diese Rechteklauseln sind vor Verwendung besonders rechtlich zu prüfen.</p></section>
<section><h2>11. Wallet und Auszahlung</h2><p>Der Auftragswert wird bei Annahme zunächst als vorgemerkt dargestellt. Eine Freigabe erfolgt nicht vor dem vorgesehenen Versand beziehungsweise der digitalen Abgabe und Abschlussprüfung. Verfügbare Beträge können ab dem konfigurierten Mindestbetrag unter Verwendung der angebotenen Auszahlungsmethoden beantragt werden. Gebühren und Nettoauszahlung werden vor Antrag angezeigt. Die Auszahlung selbst erfolgt außerhalb der Plattform und wird anschließend administrativ als ausgezahlt markiert.</p></section>
<section><h2>12. Abschlussentscheidungen</h2><p>Der Betreiber kann einen Auftrag akzeptieren, beanstanden, teilweise akzeptieren oder ablehnen. Bei Teilannahme kann ein konkreter freizugebender Betrag festgelegt werden. Innerhalb der Plattform ist kein formaler Berufungsprozess vorgesehen; zwingende gesetzliche Rechte bleiben unberührt.</p></section>
<section><h2>13. Kontolöschung</h2><p>Eine Kontolöschung erfolgt administrativ. Personenbezogene Profildaten werden gelöscht oder anonymisiert, soweit keine weitere Speicherung erforderlich ist. Rechtlich oder betrieblich erforderliche Auftrags-, Zahlungs-, Nachweis- und Rechteinformationen können erhalten bleiben. Nachweise eines gelöschten Kontos sind nicht mehr im Verkäuferinnenzugang verfügbar.</p></section>
<section><h2>14. Erlaubte und verbotene Inhalte</h2><p>Erlaubt sind ausschließlich Inhalte und Artikel, die nach den gesetzlichen Vorgaben und den jeweiligen Angebotsbedingungen zulässig sind und von der registrierten volljährigen Verkäuferin selbst stammen. Verboten sind insbesondere Inhalte mit Minderjährigen, Inhalte ohne erforderliche Einwilligung beteiligter Personen, rechtswidrige Inhalte, fremde Inhalte ohne ausreichende Rechte, heimliche Aufnahmen, gewaltverherrlichende oder sonst verbotene Inhalte sowie Gegenstände, deren Besitz, Versand oder Handel unzulässig ist.</p></section>
<section><h2>15. Systemausfälle</h2><p>Dokumentiert der Betreiber einen tatsächlichen technischen Plattformausfall, werden die dadurch betroffenen Fristen nach den Systemregeln angepasst; für den dokumentierten Ausfallzeitraum sollen keine technischen Versäumnisverstöße erzeugt werden.</p></section>
<section><h2>16. Schlussbestimmungen</h2><p>Zwingende gesetzliche Vorschriften bleiben unberührt. Sollte eine einzelne Vertragsbestimmung unwirksam sein, richtet sich die weitere Behandlung nach den gesetzlichen Vorschriften. Vor Produktivbetrieb sind insbesondere Verbraucher-, Steuer-, Gewerbe-, Datenschutz-, Jugend- und Medienrecht sowie die konkrete Rechteübertragung individuell zu prüfen.</p></section></main>